# Video Game Sales and Ratings Data

##### This dataset provides comprehensive data on video game sales, ratings, and user insights globally, including details such as the game's name, platform, year of release, genre, publisher, sales in different regions, critic and user scores, and ESRB rating.

<img src="image.png" alt="xxx" width="1650" height="330">

###  Column Descriptions

| Column | Description |
|--------|------------|
| Index | Unique identifier for each video game record. |
| Name | The name of the video game.|
| Platform | The platform on which the game is available, such as PC, PS4, Xbox, etc. |
| Year_of_Release | The year in which the game was released. |
| Genre | The genre of the game, such as Action, Sports, etc.|
| Publisher|  The company that published the game.  |
| NA_Sales| The sales of the game in North America, in millions. |
| EU_Sales| The sales of the game in Europe, in millions.|
| JP_Sales| The sales of the game in Japan, in millions. |
| Other_Sales| The sales of the game in other regions, in millions.|
| Global_Sales| The total global sales of the game, in millions. |
| Critic_Score| The average score given to the game by critics.|
| Critic_Count| The number of critics who reviewed the game.|
| User_Score| The number of critics who reviewed the game.|
| User_Count | The average score given to the game by users.|
| Developer| The company that developed the game.|
| Rating| The ESRB rating of the game, such as E for Everyone, T for Teen, or M for Mature.|

In [ ]:
# Import core libraries for data analysis and visualization.
import numpy as np
import pandas as pd
import plotly.express as px 
import matplotlib.pyplot as plt
import datetime

In [101]:
# Override default color sequence globally
my_colors= [
    "#4B0082",  # deep purple (low values)
    "#9B59B6",  # lighter purple
    "#00A86B",  # emerald green (mid values)
    "#2ECC71",  # lighter green
    "#BDC3C7"   # light gray (high values)
]
px.defaults.color_discrete_sequence = my_colors

In [102]:
# Load the dataset.
df=pd.read_csv("Video_Games.csv")
df.head()

,index,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

### Data Cleaning & Quality

In [103]:
# Convert all column names in the DataFrame to lowercase to ensures consistency and avoids issues with case sensitivity.
df.columns= df.columns.str.lower()
df.columns

Index(['index', 'name', 'platform', 'year_of_release', 'genre', 'publisher',
       'na_sales', 'eu_sales', 'jp_sales', 'other_sales', 'global_sales',
       'critic_score', 'critic_count', 'user_score', 'user_count', 'developer',
       'rating'],
      dtype='object')

In [104]:
df.shape

(16928, 17)

In [105]:
# Separate dataset’s columns into two groups: categorical variables (cat) and numerical variables (num).
cat=['name', 'platform', 'genre', 'publisher','developer', 'rating']  # contain text or categories.
num=['year_of_release', 'na_sales', 'eu_sales', 'jp_sales', 'other_sales',
       'critic_score', 'critic_count', 'user_score', 'user_count']  # contain numbers.

# Determine the target variable (sales performance).
target=['global_sales']

# Drop the 'index' column (no need it, there is a unique 'id' column in the DataFrame).
drop=['index']

In [106]:
df.drop(columns='index', axis=1, inplace=True)
df.head()

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
# Display dataFrame's summary.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16928 entries, 0 to 16927
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16926 non-null  object
 1   platform         16928 non-null  object
 2   year_of_release  16655 non-null  float64
 3   genre            16926 non-null  object
 4   publisher        16873 non-null  object
 5   na_sales         16928 non-null  float64
 6   eu_sales         16928 non-null  float64
 7   jp_sales         16928 non-null  float64
 8   other_sales      16928 non-null  float64
 9   global_sales     16928 non-null  float64
 10  critic_score     8260 non-null   float64
 11  critic_count     8260 non-null   float64
 12  user_score       10159 non-null  object
 13  user_count       7718 non-null   float64
 14  developer        10240 non-null  object
 15  rating           10092 non-null  object
dtypes: float64(9), object(7)
memory usage: 2.1+ MB

In [108]:
# Check data types of categorical columns  in 'cat'
df[cat].dtypes

name         object
platform     object
genre        object
publisher    object
developer    object
rating       object
dtype: object

In [109]:
# Check the data types of numerical columns in 'num'
df[num].dtypes

year_of_release    float64
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
critic_score       float64
critic_count       float64
user_score          object
user_count         float64
dtype: object

In [110]:
# user_score shown as object, need to repair it to be as float type.
num_repair=['user_score']

In [111]:
# Check the duplicated data.
df.duplicated().sum()

np.int64(209)

In [112]:
# Remove duplicates.
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [113]:
df.shape

(16719, 16)

In [114]:
df.describe()  # Generate descriptive statistics for all numeric columns.

,year_of_release,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_count
count,16450.000000,16719.000000,16719.000000,16719.000000,16719.000000,16719.000000,8137.000000,8137.000000,7590.000000
mean,2006.487356,0.263330,0.145025,0.077602,0.047332,0.533543,68.967679,26.360821,162.229908
std,5.878995,0.813514,0.503283,0.308818,0.186710,1.547935,13.938165,18.980495,561.282326
min,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000,13.000000,3.000000,4.000000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000,60.000000,12.000000,10.000000
50%,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000,71.000000,21.000000,24.000000
75%,2010.000000,0.240000,0.110000,0.040000,0.030000,0.470000,79.000000,36.000000,81.000000
max,2020.000000,41.360000,28.960000,10.220000,10.570000,82.530000,98.000000,113.000000,10665.000000

In [115]:
df.describe(include='object') # Generate descriptive statistics for all object-type columns.

,name,platform,genre,publisher,user_score,developer,rating
count,16717,16719,16717,16665,10015,10096,9950
unique,11562,31,12,581,96,1696,8
top,Need for Speed: Most Wanted,PS2,Action,Electronic Arts,tbd,Ubisoft,E
freq,12,2161,3370,1356,2425,204,3991

#### Check Missing Values

Drop Columns with more than 50% missing values:

In [116]:
# Check the number of missing values in each column.
df.isna().sum().sort_values(ascending=False)

user_count         9129
critic_count       8582
critic_score       8582
rating             6769
user_score         6704
developer          6623
year_of_release     269
publisher            54
name                  2
genre                 2
na_sales              0
platform              0
jp_sales              0
eu_sales              0
other_sales           0
global_sales          0
dtype: int64

In [117]:
# Calculate the percentage of missing values and Sort in descending order to see columns with the highest missing percentages first.
(df.isna().mean()*100).sort_values(ascending=False)

user_count         54.602548
critic_count       51.330821
critic_score       51.330821
rating             40.486871
user_score         40.098092
developer          39.613613
year_of_release     1.608948
publisher           0.322986
name                0.011962
genre               0.011962
na_sales            0.000000
platform            0.000000
jp_sales            0.000000
eu_sales            0.000000
other_sales         0.000000
global_sales        0.000000
dtype: float64

In [118]:
dropped_features=['user_count', 'critic_score', 'critic_count'] # more than 50 % missed values.

In [119]:
# Remove unwanted columns
drop_columns=['user_count', 'critic_score', 'critic_count']
df.drop(columns=dropped_features,axis=1,inplace=True)

In [120]:
df.columns

Index(['name', 'platform', 'year_of_release', 'genre', 'publisher', 'na_sales',
       'eu_sales', 'jp_sales', 'other_sales', 'global_sales', 'user_score',
       'developer', 'rating'],
      dtype='object')

Drop rows if missing values less than 5% of total dataset:

In [121]:
# Drop rows (with missing key fields) 
df.dropna(subset=['rating','user_score','developer','year_of_release','publisher','name','genre'])

# Percentage of rows retained 
retained=((df.dropna(subset=['rating','user_score','developer','year_of_release','publisher','name','genre'])).shape[0]/df.shape[0])*100
retained

58.047730127399966

In [122]:
# Will be removed if it's less than 5%
100- retained

41.952269872600034

Impuate remaining values for the rest columns (final_columns):

In [123]:
# Numerical columns will be filled by mean/ median.
# Categorical columns will be filled by mode.

In [124]:
# New list excluded the dropped features.

cols = df.columns.tolist() # Identify columns in the DataFrame

# Define the dropped features
dropped_features = ['user_count', 'critic_score', 'critic_count'] 

# Keep only columns that are not dropped
final_cols = [col for col in cols if col not in dropped_features]

print("Final columns:", final_cols)

Final columns: ['name', 'platform', 'year_of_release', 'genre', 'publisher', 'na_sales', 'eu_sales', 'jp_sales', 'other_sales', 'global_sales', 'user_score', 'developer', 'rating']

In [125]:
cat=['name', 'platform', 'genre', 'publisher','developer', 'rating']  # contain text or categories.
num=['year_of_release', 'na_sales', 'eu_sales', 'jp_sales', 'other_sales',
        'user_score']  # contain numbers.

#### Cleaning dataset:

In [126]:
# Inspect categorical cols: name, unique count, and unique values.
for col in cat:   
   print(col) 
   print(df[col].nunique())
   print(df[col].unique(), '\n','*'*100)

name
11562
['Wii Sports' 'Super Mario Bros.' 'Mario Kart Wii' ...
 'Woody Woodpecker in Crazy Castle 5' 'LMA Manager 2007'
 'Haitaka no Psychedelica']
 ****************************************************************************************************
platform
31
['Wii' 'NES' 'GB' 'DS' 'X360' 'PS3' 'PS2' 'SNES' 'GBA' 'PS4' '3DS' 'N64'
 'PS' 'XB' 'PC' '2600' 'PSP' 'XOne' 'WiiU' 'GC' 'GEN' 'DC' 'PSV' 'SAT'
 'SCD' 'WS' 'NG' 'TG16' '3DO' 'GG' 'PCFX']
 ****************************************************************************************************
genre
12
['Sports' 'Platform' 'Racing' 'Role-Playing' 'Puzzle' 'Misc' 'Shooter'
 'Simulation' 'Action' 'Fighting' 'Adventure' 'Strategy' nan]
 ****************************************************************************************************
publisher
581
['Nintendo' 'Microsoft Game Studios' 'Take-Two Interactive'
 'Sony Computer Entertainment' 'Activision' 'Ubisoft' 'Bethesda Softworks'
 'Electronic Arts' 'Sega' 'SquareSoft' 'Atari' '505 Games' 'Capcom'
 'GT Interactive' 'Konami Digital Entertainment' 'Square Enix'
 'Sony Computer Entertainment Europe' 'Virgin Interactive' 'LucasArts'
 'Warner Bros. Interactive Entertainment' 'Universal Interactive'
 'Eidos Interactive' 'RedOctane' 'Vivendi Games' 'Enix Corporation'
 'Namco Bandai Games' 'Palcom' 'Hasbro Interactive' 'THQ'
 'Fox Interactive' 'Acclaim Entertainment' 'MTV Games'
 'Disney Interactive Studios' nan 'Codemasters' 'Majesco Entertainment'
 'Red Orb' 'Level 5' 'Arena Entertainment' 'Midway Games' 'JVC'
 'Deep Silver' 'NCSoft' '989 Studios' 'UEP Systems' 'Parker Bros.' 'Maxis'
 'Imagic' 'Tecmo Koei' 'ASCII Entertainment' 'Valve Software' 'Mindscape'
 'Infogrames' 'Unknown' 'Square' 'Valve' 'Banpresto' 'Hello Games'
 'D3Publisher' 'Activision Value' 'Oxygen Interactive'
 'Red Storm Entertainment' 'Video System' 'Global Star' 'Gotham Games'
 'Westwood Studios' 'GungHo' 'Crave Entertainment' 'Hudson Soft' 'Coleco'
 'Rising Star Games' 'TDK Mediactive' 'ASC Games' 'Accolade' 'Zoo Games'
 'Sony Online Entertainment' '3DO' 'Natsume' 'RTL' 'Alchemist'
 'Black Label Games' 'SouthPeak Games' 'Focus Home Interactive' 'Ocean'
 'Zoo Digital Publishing' 'Psygnosis' 'City Interactive'
 'Empire Interactive' 'Success' 'Compile' 'Russel' 'Atlus' 'Mastertronic'
 'Slightly Mad Studios' 'Taito' 'Agetec' 'Microprose' 'Play It' 'GSP'
 'Tomy Corporation' 'Sammy Corporation' 'Koch Media' 'Game Factory'
 'Titus' 'Marvelous Entertainment' 'Genki' 'Mojang' 'CTO SpA' 'TalonSoft'
 'Crystal Dynamics' 'Square Enix ' 'mixi, Inc' 'Pinnacle' 'SCi' 'Quelle'
 'Rage Software' 'Ubisoft Annecy' 'Interplay' 'Scholastic Inc.' 'Mystique'
 'ChunSoft' 'Square EA' '20th Century Fox Video Games'
 'Hudson Entertainment' 'Men-A-Vision' 'Nobilis' 'Avanquest Software'
 'Big Ben Interactive' 'Nordic Games' 'Touchstone' 'Spike'
 'Nippon Ichi Software' 'Sony Computer Entertainment America'
 'Jester Interactive' 'LEGO Media' 'Quest' 'Illusion Softworks'
 'Tigervision' 'Rocket Company' 'Metro 3D' 'Mattel Interactive'
 'IE Institute' 'Funbox Media' 'Rondomedia' 'Universal Gamex' 'Ghostlight'
 'Wizard Video Games' 'BMG Interactive Entertainment' 'PQube'
 'Trion Worlds' 'Xseed Games' 'Laguna' 'Takara' 'Ignition Entertainment'
 'Kadokawa Shoten' 'Enterbrain' 'Imagineer' 'CPG Products'
 'System 3 Arcade Software' 'Aruze Corp' 'Destineer' 'Gamebridge'
 'Midas Interactive Entertainment' 'Jaleco' 'Answer Software'
 'Pack In Soft' 'XS Games' 'Rebellion' 'Ultravision'
 'Harmonix Music Systems' 'Activision Blizzard' 'Xplosiv' 'Wanadoo'
 'Telltale Games' 'NovaLogic' 'Epoch' 'BAM! Entertainment'
 'GameMill Entertainment' 'Knowledge Adventure' 'Tetris Online' 'Mastiff'
 'ESP' 'TYO' 'Telegames' 'Mud Duck Productions' 'Screenlife' 'Pioneer LDC'
 'Magical Company' 'Kemco' 'Mentor Interactive' 'Human Entertainment'
 'Data Age' 'Electronic Arts Victor' 'Jack of All Games' 'Avanquest'
 'Black Bean Games' '989 Sports' 'Takara Tomy' 'Media Rings' 'Elf'
 'Starfish' 'Zushi Games' 'Jorudan' 'Destination Software, Inc' 'New'
 'Brash Entertainment' 'Kalypso Media' 'ITT Family Games' 'Ackkstudios'
 'PopCap Games' 'Starpath Corp.' 'BPS' 'Gathering of Developers'
 'NewKidCo' 'Marvelous Interactive' 'Storm City Games' 'CokeM Interactive'
 'P2 Games' 'CBS Electronics' 'Home Entertainment Suppliers' 'Magix'
 'Arc System Works' 'Angel Studios' 'Wargaming.net' 'Playmates'
 'SNK Playmore' 'Hamster Corporation' 'From Software' 'Nippon Columbia'
 'Nichibutsu' 'Conspiracy Entertainment' 'Hect' 'Mumbo Jumbo'
 'DTP Entertainment' 'Pacific Century Cyber Works' 'Indie Games'
 'Liquid Games' 'NEC' 'Axela' 'ArtDink' 'Sunsoft' 'Little Orbit' 'FuRyu'
 'Gust' 'SNK' 'NEC Interchannel' 'Nihon Falcom Corporation'
 'Xing Entertainment' 'ValuSoft' 'Victor Interactive' 'American Softworks'
 'Falcom Corporation' 'Detn8 Games' 'Bomb' 'Nordcurrent'
 'Milestone S.r.l.' 'AQ Interactive' 'Sears' 'Seta Corporation'
 'On Demand' 'CCP' 'NCS' 'Rebellion Developments' 'Agatsuma Entertainment'
 'Gremlin Interactive Ltd' 'Aspyr' 'Compile Heart' 'Culture Brain'
 'Mad Catz' 'Shogakukan' 'Merscom LLC' 'JoWood Productions'
 'Nippon Telenet' 'TDK Core' 'Kadokawa Games' 'SSI' 'Foreign Media Games'
 'Core Design Ltd.' 'bitComposer Games' 'Astragon' 'Asylum Entertainment'
 'Performance Designed Products' 'UFO Interactive' 'Essential Games'
 'Adeline Software' 'Funcom' 'PlayV' 'Panther Software'
 'Blast! Entertainment Ltd' 'Playlogic Game Factory' 'DSI Games'
 'Avalon Interactive' 'Game Life' 'Popcorn Arcade' 'Aques' 'System 3'
 'Syscom' 'Vir2L Studios' 'Vatical Entertainment' 'Neko Entertainment'
 'White Park Bay Software' 'Vic Tokai' 'Media Factory' 'Daedalic'
 'Game Arts' 'The Adventure Company' 'EA Games' 'Acquire' 'Broccoli'
 'General Entertainment' 'Paradox Interactive' 'Yacht Club Games' 'Imadio'
 'Swing! Entertainment' 'Sony Music Entertainment' 'Aqua Plus'
 'Excalibur Publishing' 'Hip Interactive' 'Tripwire Interactive'
 'DreamCatcher Interactive' 'SCS Software' 'Havas Interactive' 'Sting'
 'Idea Factory' 'Telstar' 'U.S. Gold' 'Funsta' 'DreamWorks Interactive'
 'Slitherine Software' 'MTO' 'Graffiti' 'Tru Blu Entertainment'
 'DHM Interactive' 'Crytek' 'FunSoft' 'Data Design Interactive' 'SPS'
 'Moss' 'T&E Soft' 'NDA Productions' 'Bigben Interactive' 'Data East'
 'Idea Factory International' 'Time Warner Interactive'
 'Gainax Network Systems' 'Daito' 'O3 Entertainment' 'O-Games' 'Gameloft'
 'Xicat Interactive' 'Simon & Schuster Interactive' 'Valcon Games'
 'PopTop Software' 'TOHO' 'PM Studios' 'Bohemia Interactive'
 'Reef Entertainment' '5pb' 'HMH Interactive' 'inXile Entertainment'
 'Cave' 'Microids' 'Paon' 'CDV Software Entertainment' 'Micro Cabin'
 'GameTek' 'Benesse' 'Type-Moon' 'Enjoy Gaming ltd.' 'Asmik Corp'
 'Interplay Productions' 'Asmik Ace Entertainment' 'Image Epoch'
 'Phantom EFX' 'Evolved Games' 'responDESIGN' 'Griffin International'
 'Culture Publishers' 'Hackberry' 'Hearty Robin' 'Nippon Amuse'
 'Origin Systems' 'Seventh Chord' 'Abylight' 'Mitsui' 'Insomniac Games'
 'Flight-Plan' 'Milestone' 'Glams' 'Aksys Games' 'Locus' 'Warp'
 'Irem Software Engineering' 'Myelin Media' 'Global A Entertainment'
 'Alternative Software' 'Mercury Games' 'Sunrise Interactive' 'Elite'
 'Evolution Games' 'Daedalic Entertainment' 'Edia' 'Athena' 'Aria'
 'Tivola' 'Happinet' 'Tommo' 'Altron' 'Revolution Software' 'Media Works'
 'Fortyfive' 'Gamecock' 'Imax' '10TACLE Studios' 'Groove Games'
 'Pack-In-Video' 'Crimson Cow' 'iWin' 'Asgard' 'Ecole' 'Yumedia'
 'Ascaron Entertainment GmbH' 'HAL Laboratory' 'Phenomedia'
 'Grand Prix Games' 'DigiCube' 'Creative Core' 'Kaga Create'
 'WayForward Technologies' 'LSP Games' 'ASCII Media Works' '1C Company'
 'Coconuts Japan' 'Arika' 'Marvel Entertainment' 'Ertain' 'Prototype'
 'Phantagram' 'The Learning Company' 'TechnoSoft' 'MLB.com' 'Vap' 'Misawa'
 'Yeti' 'Dusenberry Martin Racing' 'Navarre Corp' 'Pow' 'MediaQuest'
 'Team17 Software' 'Max Five' 'Tradewest' 'Comfort' 'Milestone S.r.l'
 'Pony Canyon' 'Riverhillsoft' 'Summitsoft' 'Playmore' 'Kool Kizz'
 'Monte Christo Multimedia' 'TopWare Interactive' 'Legacy Interactive'
 'Cloud Imperium Games Corporation' 'Flashpoint Games' 'CyberFront'
 'Alawar Entertainment' 'Societa' 'Interchannel' 'Experience Inc.'
 'Sonnet' 'Virtual Play Games' 'Zenrin' 'Iceberg Interactive' 'Ivolgamus'
 'MC2 Entertainment' '2D Boy' 'Games Workshop' 'Kando Games'
 'Office Create' 'Maximum Family Games' 'Fields' 'Gearbox Software'
 'Princess Soft' 'Extreme Entertainment Group' 'Big Fish Games' 'Berkeley'
 'Mamba Games' 'Fuji' 'FuRyu Corporation' 'Her Interactive'
 'imageepoch Inc.' 'Just Flight' 'Kamui' 'ASK' 'Cygames'
 'Introversion Software' '49Games' 'KSS' 'dramatic create' 'TGL' 'KID'
 'Quinrose' 'Sold Out' 'Encore' 'G.Rev' 'Sunflowers' 'Headup Games'
 'Sweets' 'Kokopeli Digital Studios' 'id Software' 'Nexon' 'BushiRoad'
 'Devolver Digital' 'Number None' 'Tryfirst' 'GN Software' "Yuke's"
 'Strategy First' 'Lexicon Entertainment' 'Paon Corporation'
 'Kids Station' 'Licensed 4U' 'GOA' '7G//AMES' 'King Records'
 'Minato Station' 'Graphsim Entertainment' 'Easy Interactive' 'Gaga'
 'Yamasa Entertainment' 'Plenty' 'Views' 'Blue Byte' 'fonfun' 'NetRevo'
 'Epic Games' 'Quintet' 'Focus Multimedia' 'Phoenix Games'
 'Marvelous Games' 'Dorart' 'Codemasters Online' 'Stainless Games'
 'Aerosoft' 'Imageworks' 'Karin Entertainment' 'Technos Japan Corporation'
 'Masque Publishing' 'Gakken' 'New World Computing' 'Mirai Shounen'
 'Datam Polystar' 'HuneX' 'Visco' 'Saurus' 'Revolution (Japan)' 'Giza10'
 'Alvion' 'Giga' 'Mycom' 'Warashi' 'System Soft' 'RED Entertainment'
 'Lighthouse Interactive' 'Michaelsoft' 'Media Entertainment'
 'Genterprise' 'Interworks Unlimited, Inc.' 'Inti Creates' 'Boost On'
 'EON Digital Entertainment' 'Nitroplus' 'Naxat Soft' 'Piacci'
 'Paradox Development' 'Otomate' 'Ascaron Entertainment' 'Ongakukan'
 'Commseed' 'UIG Entertainment' 'Takuyo' 'Interchannel-Holon'
 'Red Flagship']
 ****************************************************************************************************
developer
1696
['Nintendo' nan 'Good Science Studio' ... 'Big Red Software'
 'Atomic Games' 'Interchannel-Holon']
 ****************************************************************************************************
rating
8
['E' nan 'M' 'T' 'E10+' 'K-A' 'AO' 'EC' 'RP']
 ****************************************************************************************************

In [127]:
# Inspect numerical cols: name, unique count, and unique values.
for col in num:   
   print(col) 
   print(df[col].nunique())
   print(df[col].unique(), '\n','*'*100)

year_of_release
39
[2006. 1985. 2008. 2009. 1996. 1989. 1984. 2005. 1999. 2007. 2010. 2013.
 2004. 1990. 1988. 2002. 2001. 2011. 1998. 2015. 2012. 2014. 1992. 1997.
 1993. 1994. 1982. 2016. 2003. 1986. 2000.   nan 1995. 1991. 1981. 1987.
 1980. 1983. 2020. 2017.]
 ****************************************************************************************************
na_sales
402
[4.136e+01 2.908e+01 1.568e+01 1.561e+01 1.127e+01 2.320e+01 1.128e+01
 1.396e+01 1.444e+01 2.693e+01 9.050e+00 9.710e+00 9.000e+00 8.920e+00
 1.500e+01 9.010e+00 7.020e+00 9.430e+00 1.278e+01 4.740e+00 6.380e+00
 1.083e+01 9.540e+00 9.660e+00 8.410e+00 6.060e+00 3.430e+00 5.510e+00
 6.850e+00 9.040e+00 5.890e+00 6.030e+00 9.700e+00 5.280e+00 4.990e+00
 8.250e+00 8.520e+00 5.540e+00 6.990e+00 6.620e+00 5.030e+00 5.990e+00
 3.960e+00 2.500e+00 7.970e+00 6.910e+00 4.340e+00 4.350e+00 3.010e+00
 6.160e+00 6.760e+00 4.020e+00 4.890e+00 2.960e+00 4.760e+00 5.010e+00
 6.730e+00 5.950e+00 3.660e+00 5.550e+00 7.040e+00 6.650e+00 3.880e+00
 5.800e+00 4.100e+00 5.930e+00 4.360e+00 5.700e+00 2.030e+00 4.400e+00
 5.050e+00 3.540e+00 1.120e+00 6.820e+00 1.750e+00 3.740e+00 1.060e+00
 2.790e+00 2.910e+00 9.900e-01 2.570e+00 2.990e+00 2.280e+00 7.280e+00
 2.760e+00 2.900e+00 2.810e+00 6.600e-01 3.780e+00 3.270e+00 3.560e+00
 5.390e+00 4.590e+00 4.810e+00 4.460e+00 3.480e+00 2.850e+00 2.530e+00
 2.980e+00 3.680e+00 3.150e+00 4.410e+00 4.120e+00 2.710e+00 2.930e+00
 3.230e+00 4.050e+00 4.150e+00 2.770e+00 3.450e+00 3.110e+00 8.400e-01
 1.660e+00 7.800e-01 2.640e+00 3.170e+00 4.980e+00 2.550e+00 3.640e+00
 3.700e+00 4.010e+00 2.470e+00 8.000e-02 3.920e+00 8.000e-01 2.450e+00
 4.470e+00 3.180e+00 2.630e+00 1.880e+00 2.410e+00 2.800e+00 6.300e-01
 2.260e+00 2.490e+00 3.570e+00 3.070e+00 2.970e+00 2.950e+00 2.540e+00
 3.280e+00 3.140e+00 4.700e-01 2.620e+00 3.210e+00 2.070e+00 2.730e+00
 1.850e+00 2.180e+00 1.740e+00 3.020e+00 1.620e+00 3.130e+00 1.920e+00
 3.330e+00 3.220e+00 2.300e+00 4.260e+00 9.700e-01 6.500e-01 1.210e+00
 1.090e+00 2.100e+00 2.440e+00 1.980e+00 3.810e+00 3.590e+00 1.630e+00
 1.960e+00 3.400e+00 6.100e-01 2.050e+00 1.700e+00 3.420e+00 3.360e+00
 3.490e+00 3.050e+00 1.830e+00 2.310e+00 3.980e+00 0.000e+00 2.600e+00
 1.910e+00 2.740e+00 2.830e+00 2.360e+00 1.730e+00 1.940e+00 2.290e+00
 1.820e+00 2.420e+00 3.040e+00 1.800e+00 2.080e+00 1.870e+00 4.180e+00
 3.190e+00 4.210e+00 3.630e+00 2.780e+00 2.000e-01 1.610e+00 1.540e+00
 2.520e+00 2.660e+00 1.000e-01 2.820e+00 2.190e+00 1.560e+00 3.030e+00
 2.200e+00 2.090e+00 2.110e+00 1.480e+00 4.000e+00 5.800e-01 2.510e+00
 3.000e+00 2.240e+00 1.460e+00 1.410e+00 9.200e-01 8.800e-01 1.280e+00
 2.250e+00 3.380e+00 2.040e+00 3.790e+00 4.030e+00 1.650e+00 7.100e-01
 1.420e+00 1.100e+00 2.320e+00 1.200e-01 2.350e+00 2.120e+00 1.400e+00
 1.680e+00 1.130e+00 1.220e+00 2.670e+00 1.020e+00 1.190e+00 1.530e+00
 2.150e+00 9.000e-01 1.970e+00 6.800e-01 1.160e+00 9.300e-01 1.440e+00
 1.600e-01 2.130e+00 2.210e+00 1.780e+00 8.600e-01 1.350e+00 1.050e+00
 2.230e+00 2.400e+00 1.370e+00 1.300e+00 1.950e+00 1.930e+00 1.330e+00
 1.490e+00 1.580e+00 5.000e-02 6.000e-01 2.020e+00 2.380e+00 1.600e+00
 2.010e+00 1.570e+00 1.230e+00 1.900e+00 2.140e+00 1.170e+00 2.270e+00
 1.640e+00 5.900e-01 1.550e+00 4.600e-01 8.100e-01 1.450e+00 2.700e-01
 1.470e+00 1.990e+00 1.500e+00 9.000e-02 2.610e+00 1.890e+00 5.000e-01
 8.900e-01 9.500e-01 2.340e+00 7.200e-01 1.720e+00 1.180e+00 1.760e+00
 7.300e-01 1.270e+00 2.060e+00 5.500e-01 1.520e+00 1.690e+00 2.170e+00
 5.100e-01 1.000e+00 1.290e+00 1.380e+00 1.150e+00 1.670e+00 1.360e+00
 1.010e+00 1.040e+00 1.840e+00 2.220e+00 7.900e-01 1.510e+00 1.070e+00
 1.320e+00 1.590e+00 2.000e-02 2.900e-01 1.250e+00 2.560e+00 1.430e+00
 1.200e+00 4.100e-01 2.800e-01 4.300e-01 6.900e-01 2.000e+00 7.600e-01
 1.860e+00 4.800e-01 6.200e-01 1.310e+00 3.700e-01 1.500e-01 6.400e-01
 2.600e-01 4.900e-01 1.110e+00 1.300e-01 1.810e+00 1.030e+00 1.260e+00
 8.700e-01 7.700e-01 9.600e-01 1.390e+00 1.080e+00 8.500e-01 9.100e-01
 3.000e-01 3.800e-01 9.400e-01 7.000e-02 1.340e+00 1.240e+00 3.400e-01
 1.400e-01 1.000e-02 5.200e-01 8.200e-01 8.300e-01 1.100e-01 2.500e-01
 1.770e+00 3.600e-01 7.500e-01 7.400e-01 1.800e-01 2.200e-01 5.300e-01
 4.200e-01 3.200e-01 3.900e-01 2.400e-01 2.300e-01 6.000e-02 4.500e-01
 7.000e-01 6.700e-01 3.500e-01 5.600e-01 1.140e+00 9.800e-01 5.700e-01
 5.400e-01 4.000e-02 1.700e-01 4.400e-01 3.000e-02 3.300e-01 3.100e-01
 4.000e-01 2.100e-01 1.900e-01]
 ****************************************************************************************************
eu_sales
307
[2.896e+01 3.580e+00 1.276e+01 1.093e+01 8.890e+00 2.260e+00 9.140e+00
 9.180e+00 6.940e+00 6.300e-01 1.095e+01 7.470e+00 6.180e+00 8.030e+00
 4.890e+00 8.490e+00 9.090e+00 4.000e-01 3.750e+00 9.200e+00 4.460e+00
 2.710e+00 3.440e+00 5.140e+00 5.490e+00 3.900e+00 5.350e+00 3.170e+00
 5.090e+00 4.240e+00 5.040e+00 5.860e+00 3.680e+00 4.190e+00 5.730e+00
 3.590e+00 4.510e+00 2.550e+00 4.020e+00 4.370e+00 6.310e+00 3.450e+00
 2.810e+00 2.850e+00 3.490e+00 1.000e-02 3.350e+00 2.040e+00 3.070e+00
 3.870e+00 3.000e+00 4.820e+00 3.640e+00 2.150e+00 3.690e+00 2.650e+00
 2.560e+00 3.110e+00 3.140e+00 1.940e+00 1.950e+00 2.470e+00 2.280e+00
 3.420e+00 3.630e+00 2.360e+00 1.710e+00 1.850e+00 2.790e+00 1.240e+00
 6.120e+00 1.530e+00 3.470e+00 2.240e+00 5.010e+00 2.010e+00 1.720e+00
 2.070e+00 6.420e+00 3.860e+00 4.500e-01 3.480e+00 1.890e+00 5.750e+00
 2.170e+00 1.370e+00 2.350e+00 1.180e+00 2.110e+00 1.880e+00 2.830e+00
 2.990e+00 2.890e+00 3.270e+00 2.220e+00 2.140e+00 1.450e+00 1.750e+00
 1.040e+00 1.770e+00 3.020e+00 2.750e+00 2.160e+00 1.900e+00 2.590e+00
 2.200e+00 4.300e+00 9.300e-01 2.530e+00 2.520e+00 1.790e+00 1.300e+00
 2.600e+00 1.580e+00 1.200e+00 1.560e+00 1.340e+00 1.260e+00 8.300e-01
 6.210e+00 2.800e+00 1.590e+00 1.730e+00 4.330e+00 1.830e+00 0.000e+00
 2.180e+00 1.980e+00 1.470e+00 6.700e-01 1.550e+00 1.910e+00 6.900e-01
 6.000e-01 1.930e+00 1.640e+00 5.500e-01 2.190e+00 1.110e+00 2.290e+00
 2.500e+00 9.600e-01 1.210e+00 1.120e+00 7.700e-01 1.690e+00 1.080e+00
 7.900e-01 2.370e+00 2.460e+00 2.600e-01 7.500e-01 1.250e+00 2.430e+00
 9.800e-01 7.400e-01 2.230e+00 6.100e-01 2.450e+00 1.410e+00 1.800e+00
 3.280e+00 1.160e+00 1.990e+00 1.380e+00 1.360e+00 1.170e+00 1.190e+00
 9.900e-01 1.680e+00 2.000e+00 1.330e+00 1.570e+00 1.480e+00 2.100e+00
 1.270e+00 1.970e+00 9.100e-01 1.390e+00 1.960e+00 2.400e-01 1.510e+00
 1.400e-01 1.290e+00 2.390e+00 1.030e+00 5.000e-01 5.800e-01 1.310e+00
 2.020e+00 1.320e+00 1.010e+00 2.270e+00 2.300e+00 1.820e+00 2.780e+00
 4.400e-01 4.800e-01 2.700e-01 2.100e-01 2.480e+00 5.100e-01 1.520e+00
 4.000e-02 2.800e-01 1.350e+00 8.700e-01 2.130e+00 1.130e+00 1.760e+00
 7.600e-01 2.120e+00 6.600e-01 1.600e+00 1.440e+00 1.430e+00 1.700e+00
 4.700e-01 1.870e+00 8.600e-01 7.300e-01 1.280e+00 8.100e-01 1.090e+00
 6.800e-01 1.220e+00 1.400e+00 1.020e+00 1.490e+00 1.140e+00 4.900e-01
 9.000e-01 3.800e-01 1.420e+00 9.500e-01 1.620e+00 7.100e-01 1.050e+00
 9.200e-01 3.300e-01 3.000e-01 1.670e+00 1.000e+00 8.900e-01 1.000e-01
 7.200e-01 5.900e-01 5.600e-01 1.600e-01 9.700e-01 6.200e-01 8.500e-01
 9.400e-01 8.800e-01 8.400e-01 1.060e+00 2.000e-01 1.150e+00 8.000e-01
 1.100e+00 7.000e-01 1.920e+00 3.200e-01 1.500e-01 5.300e-01 9.000e-02
 1.460e+00 2.900e-01 2.200e-01 1.230e+00 7.000e-02 1.700e-01 5.400e-01
 3.600e-01 3.100e-01 1.840e+00 5.200e-01 1.100e-01 6.400e-01 1.200e-01
 2.050e+00 1.630e+00 8.200e-01 8.000e-02 5.700e-01 1.650e+00 1.900e-01
 2.000e-02 4.300e-01 2.500e-01 1.500e+00 1.800e-01 3.900e-01 1.300e-01
 1.070e+00 4.600e-01 4.100e-01 6.000e-02 3.000e-02 3.700e-01 5.000e-02
 2.300e-01 6.500e-01 4.200e-01 3.400e-01 3.500e-01 7.800e-01]
 ****************************************************************************************************
jp_sales
244
[3.770e+00 6.810e+00 3.790e+00 3.280e+00 1.022e+01 4.220e+00 6.500e+00
 2.930e+00 4.700e+00 2.800e-01 1.930e+00 4.130e+00 7.200e+00 3.600e+00
 2.400e-01 2.530e+00 9.800e-01 4.100e-01 3.540e+00 4.160e+00 6.040e+00
 4.180e+00 3.840e+00 6.000e-02 4.700e-01 5.380e+00 5.320e+00 5.650e+00
 1.870e+00 1.300e-01 3.120e+00 3.600e-01 1.100e-01 4.350e+00 6.500e-01
 7.000e-02 8.000e-02 4.900e-01 3.000e-01 2.660e+00 2.690e+00 4.800e-01
 3.800e-01 5.330e+00 1.910e+00 3.960e+00 3.100e+00 1.100e+00 1.200e+00
 1.400e-01 2.540e+00 2.140e+00 8.100e-01 2.120e+00 4.400e-01 3.150e+00
 1.250e+00 4.000e-02 0.000e+00 2.470e+00 2.230e+00 1.690e+00 1.000e-02
 3.000e+00 2.000e-02 4.390e+00 1.980e+00 1.000e-01 3.810e+00 5.000e-02
 2.490e+00 1.580e+00 3.140e+00 2.730e+00 6.600e-01 2.200e-01 3.630e+00
 1.450e+00 1.310e+00 2.430e+00 7.000e-01 3.500e-01 1.400e+00 6.000e-01
 2.260e+00 1.420e+00 1.280e+00 1.390e+00 8.700e-01 1.700e-01 9.400e-01
 1.900e-01 2.100e-01 1.600e+00 1.600e-01 1.030e+00 2.500e-01 2.060e+00
 1.490e+00 1.290e+00 9.000e-02 2.870e+00 3.000e-02 7.800e-01 8.300e-01
 2.330e+00 2.020e+00 1.360e+00 1.810e+00 1.970e+00 9.100e-01 9.900e-01
 9.500e-01 2.000e+00 1.010e+00 2.780e+00 2.110e+00 1.090e+00 2.000e-01
 1.900e+00 1.270e+00 3.610e+00 1.570e+00 2.200e+00 1.700e+00 1.080e+00
 1.500e-01 1.110e+00 2.900e-01 1.540e+00 1.200e-01 8.900e-01 4.870e+00
 1.520e+00 1.320e+00 1.150e+00 4.100e+00 1.460e+00 4.600e-01 1.050e+00
 1.610e+00 2.600e-01 1.380e+00 6.200e-01 7.300e-01 5.700e-01 3.100e-01
 5.800e-01 1.760e+00 2.100e+00 9.000e-01 5.100e-01 6.400e-01 2.460e+00
 2.300e-01 3.700e-01 9.200e-01 1.070e+00 2.620e+00 1.120e+00 5.400e-01
 2.700e-01 5.900e-01 3.670e+00 5.500e-01 1.750e+00 3.440e+00 3.300e-01
 2.550e+00 2.320e+00 2.790e+00 7.400e-01 3.180e+00 8.200e-01 7.700e-01
 4.000e-01 2.350e+00 3.190e+00 8.000e-01 7.600e-01 3.030e+00 8.800e-01
 4.500e-01 1.160e+00 3.400e-01 1.190e+00 1.130e+00 2.130e+00 1.960e+00
 7.100e-01 1.040e+00 2.680e+00 6.800e-01 2.650e+00 9.600e-01 2.410e+00
 5.200e-01 1.800e-01 1.340e+00 1.480e+00 2.340e+00 1.060e+00 1.210e+00
 2.290e+00 1.630e+00 2.050e+00 2.170e+00 1.560e+00 1.350e+00 1.330e+00
 6.300e-01 7.900e-01 7.500e-01 5.300e-01 1.530e+00 1.300e+00 3.900e-01
 6.900e-01 4.200e-01 9.300e-01 5.600e-01 8.400e-01 7.200e-01 3.200e-01
 1.710e+00 1.650e+00 6.100e-01 1.510e+00 1.500e+00 1.440e+00 1.240e+00
 1.180e+00 1.370e+00 1.000e+00 1.260e+00 8.500e-01 4.300e-01 6.700e-01
 1.140e+00 8.600e-01 1.170e+00 5.000e-01 1.020e+00 9.700e-01]
 ****************************************************************************************************
other_sales
155
[8.450e+00 7.700e-01 3.290e+00 2.950e+00 1.000e+00 5.800e-01 2.880e+00
 2.840e+00 2.240e+00 4.700e-01 2.740e+00 1.900e+00 7.100e-01 2.150e+00
 1.690e+00 1.770e+00 3.960e+00 1.057e+01 5.500e-01 2.040e+00 1.360e+00
 4.200e-01 4.600e-01 1.410e+00 1.780e+00 5.000e-01 1.180e+00 8.000e-01
 1.160e+00 1.320e+00 5.900e-01 2.380e+00 1.130e+00 7.800e-01 2.420e+00
 1.120e+00 1.280e+00 1.570e+00 1.300e+00 1.010e+00 9.100e-01 1.790e+00
 1.970e+00 8.600e-01 1.210e+00 2.300e-01 7.600e-01 7.400e-01 7.530e+00
 2.900e-01 1.030e+00 5.200e-01 2.110e+00 1.600e+00 1.610e+00 3.500e-01
 9.700e-01 1.060e+00 6.300e-01 1.500e-01 7.900e-01 9.600e-01 1.250e+00
 9.000e-01 8.100e-01 3.900e-01 6.800e-01 8.500e-01 1.800e-01 8.000e-02
 6.700e-01 7.000e-01 4.100e-01 3.300e-01 6.000e-01 5.400e-01 1.730e+00
 1.230e+00 1.600e-01 1.110e+00 3.100e-01 4.800e-01 6.200e-01 1.900e-01
 6.900e-01 1.020e+00 7.300e-01 1.080e+00 4.500e-01 2.800e-01 5.100e-01
 2.200e-01 1.090e+00 9.900e-01 3.000e-01 6.400e-01 6.600e-01 9.800e-01
 1.390e+00 1.400e-01 1.370e+00 7.000e-02 2.100e-01 6.100e-01 1.700e-01
 1.200e-01 0.000e+00 7.200e-01 2.400e-01 8.200e-01 1.740e+00 8.700e-01
 9.200e-01 5.700e-01 1.100e-01 4.000e-02 5.600e-01 2.000e-01 3.400e-01
 9.000e-02 8.300e-01 4.400e-01 6.000e-02 3.200e-01 3.800e-01 1.480e+00
 3.700e-01 1.000e-01 2.500e-01 3.600e-01 1.300e-01 4.300e-01 5.000e-02
 2.000e-02 2.600e-01 4.000e-01 7.500e-01 1.930e+00 8.400e-01 5.300e-01
 8.900e-01 1.670e+00 2.700e-01 2.930e+00 4.900e-01 1.000e-02 2.460e+00
 3.000e-02 1.510e+00 2.050e+00 1.680e+00 1.820e+00 1.330e+00 9.400e-01
 9.300e-01]
 ****************************************************************************************************
user_score
96
['8' nan '8.3' '8.5' '6.6' '8.4' '8.6' '7.7' '6.3' '7.4' '8.2' '9' '7.9'
 '8.1' '8.7' '7.1' '3.4' '5.3' '4.8' '3.2' '8.9' '6.4' '7.8' '7.5' '2.6'
 '7.2' '9.2' '7' '7.3' '4.3' '7.6' '5.7' '5' '9.1' '6.5' 'tbd' '8.8' '6.9'
 '9.4' '6.8' '6.1' '6.7' '5.4' '4' '4.9' '4.5' '9.3' '6.2' '4.2' '6' '3.7'
 '4.1' '5.8' '5.6' '5.5' '4.4' '4.6' '5.9' '3.9' '3.1' '2.9' '5.2' '3.3'
 '4.7' '5.1' '3.5' '2.5' '1.9' '3' '2.7' '2.2' '2' '9.5' '2.1' '3.6' '2.8'
 '1.8' '3.8' '0' '1.6' '9.6' '2.4' '1.7' '1.1' '0.3' '1.5' '0.7' '1.2'
 '2.3' '0.5' '1.3' '0.2' '0.6' '1.4' '0.9' '1' '9.7']
 ****************************************************************************************************

In [128]:
# Show all values in the target column
print(df[target].values)

[[8.253e+01]
 [4.024e+01]
 [3.552e+01]
 ...
 [1.000e-02]
 [1.000e-02]
 [1.000e-02]]

## Repairing Columns:

#### Detecting and fixing problems in dataset columns such as inconsistent formats, wrong data types, or invalid entries.

In [129]:
repair_columns=['year_of_release', 'publisher', 'na_sales', 'eu_sales', 'jp_sales','other_sales','global_sales','user_score']

In [130]:
""" 
    - Convert all object dtype to string dtype: optimized internally, making operations faster and more memory efficient.
    - year_of_release: contain 'Adventure'(invalid entry) will replace it with NaN (becuase it is wrong value that is belong to year) 
                     and convert the data type from float into int (ex: from [2006.] to [2006]), then fill it.
                   
    - publisher: need to remove the puncatiations: , - // . to be better.
    - na_sales, eu_sales, jp_sales, other_sales and global_sales: need to convert the scientific notation (like 4.136e+01) into standard decimal formatting (like 41.36) to be clear and more readable.
    - user_score: need to replace 'tbd' to NaN and convert the data type from object into float, then fill it. 
      
"""

" \n    - Convert all object dtype to string dtype: optimized internally, making operations faster and more memory efficient.\n    - year_of_release: contain 'Adventure'(invalid entry) will replace it with NaN (becuase it is wrong value that is belong to year) \n                     and convert the data type from float into int (ex: from [2006.] to [2006]), then fill it.\n                   \n    - publisher: need to remove the puncatiations: , - // . to be better.\n    - na_sales, eu_sales, jp_sales, other_sales and global_sales: need to convert the scientific notation (like 4.136e+01) into standard decimal formatting (like 41.36) to be clear and more readable.\n    - user_score: need to replace 'tbd' to NaN and convert the data type from object into float, then fill it. \n      \n"

Convert all object dtype to string dtype

In [197]:
# Identify object columns
obj_cols = df.select_dtypes(include='object').columns
print(obj_cols)

Index(['na_sales', 'eu_sales', 'jp_sales', 'other_sales', 'sales_category',
       'game_age_category'],
      dtype='object')

In [198]:
# Convert them to pandas string dtype
df[obj_cols] = df[obj_cols].astype("string")

# Verify conversion
print(df.dtypes)

name                 string[python]
platform             string[python]
year_of_release               Int64
genre                string[python]
publisher            string[python]
na_sales             string[python]
eu_sales             string[python]
jp_sales             string[python]
other_sales          string[python]
global_sales                float64
user_score                  float64
developer            string[python]
rating               string[python]
sales_category       string[python]
game_age                      Int64
game_age_category    string[python]
dtype: object

In [133]:
# Repair 'year_of_release' column

# Step1: Convert 'year_of_release' to numeric, invalid entries (like: Adventure) → NaN
df['year_of_release'] = pd.to_numeric(df['year_of_release'], errors='coerce') 

# Step2: convert to Int to remove float decimals (e.g., 2009.0 → 2009).
df['year_of_release'] = df['year_of_release'].astype('Int64')  

# Check unique values
df['year_of_release'].unique()

<IntegerArray>
[2006, 1985, 2008, 2009, 1996, 1989, 1984, 2005, 1999, 2007, 2010, 2013, 2004,
 1990, 1988, 2002, 2001, 2011, 1998, 2015, 2012, 2014, 1992, 1997, 1993, 1994,
 1982, 2016, 2003, 1986, 2000, <NA>, 1995, 1991, 1981, 1987, 1980, 1983, 2020,
 2017]
Length: 40, dtype: Int64

In [134]:
# Repair the 'publisher' column: need to remove the puncatiations: '-' , '.' , '//' , ',' to be better.
df['publisher'] = (
    df['publisher']
    .str.strip()
    .str.lower()
    .str.replace('-', ' ')
    .str.replace('.', ' ')
    .str.replace('//', ' ')
    .str.replace(',', ' ')
)

In [135]:
# Run it after repair to see the changes:
print('publisher') 
print(df['publisher'].nunique())
print(df['publisher'].unique())

publisher
580
<StringArray>
[                   'nintendo',      'microsoft game studios',
        'take two interactive', 'sony computer entertainment',
                  'activision',                     'ubisoft',
          'bethesda softworks',             'electronic arts',
                        'sega',                  'squaresoft',
 ...
                      'piacci',         'paradox development',
                     'otomate',       'ascaron entertainment',
                   'ongakukan',                    'commseed',
           'uig entertainment',                      'takuyo',
          'interchannel holon',                'red flagship']
Length: 581, dtype: string

In [136]:
# Repair cols_to_format
cols_to_format=['na_sales','eu_sales','jp_sales','other_sales','global_sales']

# Define function for decimal formatting.
def decimal_format(x, decimals=2):
    if pd.isna(x):   # to keep NaN as it is.
        return x
    else:
        return format(float(x), f'.{decimals}f')

In [137]:
# Apply formatting function.
for col in cols_to_format:
    df[col]=df[col].apply(decimal_format)

In [138]:
for col in cols_to_format:  # to check the output
    print(col) 
    print(df[col].nunique())
    print(df[col].unique(), '\n','*'*100)

na_sales
402
['41.36' '29.08' '15.68' '15.61' '11.27' '23.20' '11.28' '13.96' '14.44'
 '26.93' '9.05' '9.71' '9.00' '8.92' '15.00' '9.01' '7.02' '9.43' '12.78'
 '4.74' '6.38' '10.83' '9.54' '9.66' '8.41' '6.06' '3.43' '5.51' '6.85'
 '9.04' '5.89' '6.03' '9.70' '5.28' '4.99' '8.25' '8.52' '5.54' '6.99'
 '6.62' '5.03' '5.99' '3.96' '2.50' '7.97' '6.91' '4.34' '4.35' '3.01'
 '6.16' '6.76' '4.02' '4.89' '2.96' '4.76' '5.01' '6.73' '5.95' '3.66'
 '5.55' '7.04' '6.65' '3.88' '5.80' '4.10' '5.93' '4.36' '5.70' '2.03'
 '4.40' '5.05' '3.54' '1.12' '6.82' '1.75' '3.74' '1.06' '2.79' '2.91'
 '0.99' '2.57' '2.99' '2.28' '7.28' '2.76' '2.90' '2.81' '0.66' '3.78'
 '3.27' '3.56' '5.39' '4.59' '4.81' '4.46' '3.48' '2.85' '2.53' '2.98'
 '3.68' '3.15' '4.41' '4.12' '2.71' '2.93' '3.23' '4.05' '4.15' '2.77'
 '3.45' '3.11' '0.84' '1.66' '0.78' '2.64' '3.17' '4.98' '2.55' '3.64'
 '3.70' '4.01' '2.47' '0.08' '3.92' '0.80' '2.45' '4.47' '3.18' '2.63'
 '1.88' '2.41' '2.80' '0.63' '2.26' '2.49' '3.57' '3.07' '2.97' '2.95'
 '2.54' '3.28' '3.14' '0.47' '2.62' '3.21' '2.07' '2.73' '1.85' '2.18'
 '1.74' '3.02' '1.62' '3.13' '1.92' '3.33' '3.22' '2.30' '4.26' '0.97'
 '0.65' '1.21' '1.09' '2.10' '2.44' '1.98' '3.81' '3.59' '1.63' '1.96'
 '3.40' '0.61' '2.05' '1.70' '3.42' '3.36' '3.49' '3.05' '1.83' '2.31'
 '3.98' '0.00' '2.60' '1.91' '2.74' '2.83' '2.36' '1.73' '1.94' '2.29'
 '1.82' '2.42' '3.04' '1.80' '2.08' '1.87' '4.18' '3.19' '4.21' '3.63'
 '2.78' '0.20' '1.61' '1.54' '2.52' '2.66' '0.10' '2.82' '2.19' '1.56'
 '3.03' '2.20' '2.09' '2.11' '1.48' '4.00' '0.58' '2.51' '3.00' '2.24'
 '1.46' '1.41' '0.92' '0.88' '1.28' '2.25' '3.38' '2.04' '3.79' '4.03'
 '1.65' '0.71' '1.42' '1.10' '2.32' '0.12' '2.35' '2.12' '1.40' '1.68'
 '1.13' '1.22' '2.67' '1.02' '1.19' '1.53' '2.15' '0.90' '1.97' '0.68'
 '1.16' '0.93' '1.44' '0.16' '2.13' '2.21' '1.78' '0.86' '1.35' '1.05'
 '2.23' '2.40' '1.37' '1.30' '1.95' '1.93' '1.33' '1.49' '1.58' '0.05'
 '0.60' '2.02' '2.38' '1.60' '2.01' '1.57' '1.23' '1.90' '2.14' '1.17'
 '2.27' '1.64' '0.59' '1.55' '0.46' '0.81' '1.45' '0.27' '1.47' '1.99'
 '1.50' '0.09' '2.61' '1.89' '0.50' '0.89' '0.95' '2.34' '0.72' '1.72'
 '1.18' '1.76' '0.73' '1.27' '2.06' '0.55' '1.52' '1.69' '2.17' '0.51'
 '1.00' '1.29' '1.38' '1.15' '1.67' '1.36' '1.01' '1.04' '1.84' '2.22'
 '0.79' '1.51' '1.07' '1.32' '1.59' '0.02' '0.29' '1.25' '2.56' '1.43'
 '1.20' '0.41' '0.28' '0.43' '0.69' '2.00' '0.76' '1.86' '0.48' '0.62'
 '1.31' '0.37' '0.15' '0.64' '0.26' '0.49' '1.11' '0.13' '1.81' '1.03'
 '1.26' '0.87' '0.77' '0.96' '1.39' '1.08' '0.85' '0.91' '0.30' '0.38'
 '0.94' '0.07' '1.34' '1.24' '0.34' '0.14' '0.01' '0.52' '0.82' '0.83'
 '0.11' '0.25' '1.77' '0.36' '0.75' '0.74' '0.18' '0.22' '0.53' '0.42'
 '0.32' '0.39' '0.24' '0.23' '0.06' '0.45' '0.70' '0.67' '0.35' '0.56'
 '1.14' '0.98' '0.57' '0.54' '0.04' '0.17' '0.44' '0.03' '0.33' '0.31'
 '0.40' '0.21' '0.19']
 ****************************************************************************************************
eu_sales
307
['28.96' '3.58' '12.76' '10.93' '8.89' '2.26' '9.14' '9.18' '6.94' '0.63'
 '10.95' '7.47' '6.18' '8.03' '4.89' '8.49' '9.09' '0.40' '3.75' '9.20'
 '4.46' '2.71' '3.44' '5.14' '5.49' '3.90' '5.35' '3.17' '5.09' '4.24'
 '5.04' '5.86' '3.68' '4.19' '5.73' '3.59' '4.51' '2.55' '4.02' '4.37'
 '6.31' '3.45' '2.81' '2.85' '3.49' '0.01' '3.35' '2.04' '3.07' '3.87'
 '3.00' '4.82' '3.64' '2.15' '3.69' '2.65' '2.56' '3.11' '3.14' '1.94'
 '1.95' '2.47' '2.28' '3.42' '3.63' '2.36' '1.71' '1.85' '2.79' '1.24'
 '6.12' '1.53' '3.47' '2.24' '5.01' '2.01' '1.72' '2.07' '6.42' '3.86'
 '0.45' '3.48' '1.89' '5.75' '2.17' '1.37' '2.35' '1.18' '2.11' '1.88'
 '2.83' '2.99' '2.89' '3.27' '2.22' '2.14' '1.45' '1.75' '1.04' '1.77'
 '3.02' '2.75' '2.16' '1.90' '2.59' '2.20' '4.30' '0.93' '2.53' '2.52'
 '1.79' '1.30' '2.60' '1.58' '1.20' '1.56' '1.34' '1.26' '0.83' '6.21'
 '2.80' '1.59' '1.73' '4.33' '1.83' '0.00' '2.18' '1.98' '1.47' '0.67'
 '1.55' '1.91' '0.69' '0.60' '1.93' '1.64' '0.55' '2.19' '1.11' '2.29'
 '2.50' '0.96' '1.21' '1.12' '0.77' '1.69' '1.08' '0.79' '2.37' '2.46'
 '0.26' '0.75' '1.25' '2.43' '0.98' '0.74' '2.23' '0.61' '2.45' '1.41'
 '1.80' '3.28' '1.16' '1.99' '1.38' '1.36' '1.17' '1.19' '0.99' '1.68'
 '2.00' '1.33' '1.57' '1.48' '2.10' '1.27' '1.97' '0.91' '1.39' '1.96'
 '0.24' '1.51' '0.14' '1.29' '2.39' '1.03' '0.50' '0.58' '1.31' '2.02'
 '1.32' '1.01' '2.27' '2.30' '1.82' '2.78' '0.44' '0.48' '0.27' '0.21'
 '2.48' '0.51' '1.52' '0.04' '0.28' '1.35' '0.87' '2.13' '1.13' '1.76'
 '0.76' '2.12' '0.66' '1.60' '1.44' '1.43' '1.70' '0.47' '1.87' '0.86'
 '0.73' '1.28' '0.81' '1.09' '0.68' '1.22' '1.40' '1.02' '1.49' '1.14'
 '0.49' '0.90' '0.38' '1.42' '0.95' '1.62' '0.71' '1.05' '0.92' '0.33'
 '0.30' '1.67' '1.00' '0.89' '0.10' '0.72' '0.59' '0.56' '0.16' '0.97'
 '0.62' '0.85' '0.94' '0.88' '0.84' '1.06' '0.20' '1.15' '0.80' '1.10'
 '0.70' '1.92' '0.32' '0.15' '0.53' '0.09' '1.46' '0.29' '0.22' '1.23'
 '0.07' '0.17' '0.54' '0.36' '0.31' '1.84' '0.52' '0.11' '0.64' '0.12'
 '2.05' '1.63' '0.82' '0.08' '0.57' '1.65' '0.19' '0.02' '0.43' '0.25'
 '1.50' '0.18' '0.39' '0.13' '1.07' '0.46' '0.41' '0.06' '0.03' '0.37'
 '0.05' '0.23' '0.65' '0.42' '0.34' '0.35' '0.78']
 ****************************************************************************************************
jp_sales
244
['3.77' '6.81' '3.79' '3.28' '10.22' '4.22' '6.50' '2.93' '4.70' '0.28'
 '1.93' '4.13' '7.20' '3.60' '0.24' '2.53' '0.98' '0.41' '3.54' '4.16'
 '6.04' '4.18' '3.84' '0.06' '0.47' '5.38' '5.32' '5.65' '1.87' '0.13'
 '3.12' '0.36' '0.11' '4.35' '0.65' '0.07' '0.08' '0.49' '0.30' '2.66'
 '2.69' '0.48' '0.38' '5.33' '1.91' '3.96' '3.10' '1.10' '1.20' '0.14'
 '2.54' '2.14' '0.81' '2.12' '0.44' '3.15' '1.25' '0.04' '0.00' '2.47'
 '2.23' '1.69' '0.01' '3.00' '0.02' '4.39' '1.98' '0.10' '3.81' '0.05'
 '2.49' '1.58' '3.14' '2.73' '0.66' '0.22' '3.63' '1.45' '1.31' '2.43'
 '0.70' '0.35' '1.40' '0.60' '2.26' '1.42' '1.28' '1.39' '0.87' '0.17'
 '0.94' '0.19' '0.21' '1.60' '0.16' '1.03' '0.25' '2.06' '1.49' '1.29'
 '0.09' '2.87' '0.03' '0.78' '0.83' '2.33' '2.02' '1.36' '1.81' '1.97'
 '0.91' '0.99' '0.95' '2.00' '1.01' '2.78' '2.11' '1.09' '0.20' '1.90'
 '1.27' '3.61' '1.57' '2.20' '1.70' '1.08' '0.15' '1.11' '0.29' '1.54'
 '0.12' '0.89' '4.87' '1.52' '1.32' '1.15' '4.10' '1.46' '0.46' '1.05'
 '1.61' '0.26' '1.38' '0.62' '0.73' '0.57' '0.31' '0.58' '1.76' '2.10'
 '0.90' '0.51' '0.64' '2.46' '0.23' '0.37' '0.92' '1.07' '2.62' '1.12'
 '0.54' '0.27' '0.59' '3.67' '0.55' '1.75' '3.44' '0.33' '2.55' '2.32'
 '2.79' '0.74' '3.18' '0.82' '0.77' '0.40' '2.35' '3.19' '0.80' '0.76'
 '3.03' '0.88' '0.45' '1.16' '0.34' '1.19' '1.13' '2.13' '1.96' '0.71'
 '1.04' '2.68' '0.68' '2.65' '0.96' '2.41' '0.52' '0.18' '1.34' '1.48'
 '2.34' '1.06' '1.21' '2.29' '1.63' '2.05' '2.17' '1.56' '1.35' '1.33'
 '0.63' '0.79' '0.75' '0.53' '1.53' '1.30' '0.39' '0.69' '0.42' '0.93'
 '0.56' '0.84' '0.72' '0.32' '1.71' '1.65' '0.61' '1.51' '1.50' '1.44'
 '1.24' '1.18' '1.37' '1.00' '1.26' '0.85' '0.43' '0.67' '1.14' '0.86'
 '1.17' '0.50' '1.02' '0.97']
 ****************************************************************************************************
other_sales
155
['8.45' '0.77' '3.29' '2.95' '1.00' '0.58' '2.88' '2.84' '2.24' '0.47'
 '2.74' '1.90' '0.71' '2.15' '1.69' '1.77' '3.96' '10.57' '0.55' '2.04'
 '1.36' '0.42' '0.46' '1.41' '1.78' '0.50' '1.18' '0.80' '1.16' '1.32'
 '0.59' '2.38' '1.13' '0.78' '2.42' '1.12' '1.28' '1.57' '1.30' '1.01'
 '0.91' '1.79' '1.97' '0.86' '1.21' '0.23' '0.76' '0.74' '7.53' '0.29'
 '1.03' '0.52' '2.11' '1.60' '1.61' '0.35' '0.97' '1.06' '0.63' '0.15'
 '0.79' '0.96' '1.25' '0.90' '0.81' '0.39' '0.68' '0.85' '0.18' '0.08'
 '0.67' '0.70' '0.41' '0.33' '0.60' '0.54' '1.73' '1.23' '0.16' '1.11'
 '0.31' '0.48' '0.62' '0.19' '0.69' '1.02' '0.73' '1.08' '0.45' '0.28'
 '0.51' '0.22' '1.09' '0.99' '0.30' '0.64' '0.66' '0.98' '1.39' '0.14'
 '1.37' '0.07' '0.21' '0.61' '0.17' '0.12' '0.00' '0.72' '0.24' '0.82'
 '1.74' '0.87' '0.92' '0.57' '0.11' '0.04' '0.56' '0.20' '0.34' '0.09'
 '0.83' '0.44' '0.06' '0.32' '0.38' '1.48' '0.37' '0.10' '0.25' '0.36'
 '0.13' '0.43' '0.05' '0.02' '0.26' '0.40' '0.75' '1.93' '0.84' '0.53'
 '0.89' '1.67' '0.27' '2.93' '0.49' '0.01' '2.46' '0.03' '1.51' '2.05'
 '1.68' '1.82' '1.33' '0.94' '0.93']
 ****************************************************************************************************
global_sales
629
['82.53' '40.24' '35.52' '32.77' '31.37' '30.26' '29.80' '28.92' '28.32'
 '28.31' '24.67' '23.21' '23.10' '22.70' '21.81' '21.79' '21.04' '20.81'
 '20.61' '20.15' '18.25' '18.14' '17.28' '16.27' '16.15' '15.85' '15.29'
 '15.14' '14.98' '14.73' '14.64' '14.63' '14.61' '14.60' '13.79' '13.67'
 '13.47' '13.32' '13.10' '12.84' '12.66' '12.63' '12.61' '12.13' '12.12'
 '11.89' '11.77' '11.68' '11.66' '11.35' '11.18' '11.01' '10.95' '10.81'
 '10.70' '10.60' '10.55' '10.50' '10.49' '10.30' '10.25' '10.12' '9.90'
 '9.87' '9.86' '9.72' '9.71' '9.49' '9.44' '9.36' '9.31' '9.30' '9.18'
 '9.16' '8.91' '8.79' '8.76' '8.57' '8.49' '8.38' '8.27' '8.16' '8.09'
 '8.07' '8.05' '8.01' '7.99' '7.98' '7.86' '7.81' '7.72' '7.69' '7.66'
 '7.60' '7.59' '7.58' '7.55' '7.51' '7.46' '7.39' '7.38' '7.32' '7.20'
 '7.17' '7.16' '7.15' '7.14' '7.13' '7.09' '7.07' '6.95' '6.90' '6.83'
 '6.82' '6.76' '6.75' '6.74' '6.71' '6.68' '6.66' '6.65' '6.62' '6.51'
 '6.49' '6.47' '6.45' '6.44' '6.43' '6.41' '6.40' '6.39' '6.34' '6.32'
 '6.31' '6.30' '6.29' '6.27' '6.21' '6.19' '6.09' '6.08' '6.05' '6.03'
 '5.99' '5.95' '5.87' '5.82' '5.78' '5.74' '5.64' '5.63' '5.58' '5.55'
 '5.54' '5.49' '5.48' '5.47' '5.46' '5.45' '5.42' '5.39' '5.38' '5.34'
 '5.33' '5.31' '5.30' '5.29' '5.27' '5.26' '5.24' '5.23' '5.22' '5.21'
 '5.20' '5.19' '5.16' '5.15' '5.14' '5.13' '5.12' '5.10' '5.09' '5.08'
 '5.07' '5.05' '5.03' '5.02' '5.01' '5.00' '4.98' '4.93' '4.92' '4.91'
 '4.88' '4.87' '4.85' '4.84' '4.82' '4.80' '4.79' '4.76' '4.73' '4.71'
 '4.70' '4.68' '4.67' '4.63' '4.62' '4.61' '4.60' '4.59' '4.57' '4.53'
 '4.50' '4.49' '4.48' '4.47' '4.46' '4.45' '4.43' '4.42' '4.41' '4.39'
 '4.38' '4.37' '4.36' '4.34' '4.33' '4.32' '4.31' '4.29' '4.28' '4.27'
 '4.24' '4.23' '4.22' '4.21' '4.20' '4.19' '4.18' '4.17' '4.16' '4.14'
 '4.12' '4.11' '4.10' '4.09' '4.08' '4.07' '4.06' '4.05' '4.04' '4.03'
 '4.01' '3.98' '3.97' '3.96' '3.95' '3.94' '3.91' '3.90' '3.89' '3.88'
 '3.87' '3.85' '3.84' '3.83' '3.80' '3.79' '3.77' '3.76' '3.74' '3.73'
 '3.72' '3.71' '3.70' '3.67' '3.66' '3.65' '3.64' '3.63' '3.62' '3.61'
 '3.60' '3.59' '3.58' '3.56' '3.54' '3.53' '3.52' '3.51' '3.50' '3.49'
 '3.48' '3.47' '3.46' '3.45' '3.44' '3.42' '3.41' '3.40' '3.39' '3.38'
 '3.37' '3.36' '3.35' '3.34' '3.33' '3.32' '3.31' '3.30' '3.28' '3.27'
 '3.26' '3.25' '3.24' '3.23' '3.21' '3.20' '3.19' '3.18' '3.17' '3.15'
 '3.14' '3.13' '3.12' '3.11' '3.10' '3.09' '3.08' '3.07' '3.06' '3.05'
 '3.04' '3.03' '3.02' '3.01' '3.00' '2.99' '2.96' '2.95' '2.94' '2.93'
 '2.92' '2.91' '2.90' '2.89' '2.88' '2.87' '2.86' '2.85' '2.84' '2.83'
 '2.82' '2.81' '2.80' '2.79' '2.78' '2.77' '2.76' '2.75' '2.73' '2.71'
 '2.70' '2.69' '2.68' '2.67' '2.66' '2.65' '2.63' '2.62' '2.61' '2.60'
 '2.59' '2.58' '2.57' '2.56' '2.54' '2.53' '2.52' '2.50' '2.49' '2.48'
 '2.47' '2.46' '2.45' '2.44' '2.43' '2.42' '2.41' '2.40' '2.39' '2.38'
 '2.37' '2.36' '2.35' '2.34' '2.32' '2.31' '2.30' '2.29' '2.28' '2.27'
 '2.26' '2.25' '2.24' '2.23' '2.22' '2.21' '2.20' '2.19' '2.18' '2.17'
 '2.16' '2.15' '2.14' '2.13' '2.12' '2.11' '2.10' '2.09' '2.08' '2.07'
 '2.06' '2.05' '2.04' '2.03' '2.02' '2.01' '2.00' '1.99' '1.98' '1.97'
 '1.96' '1.95' '1.94' '1.93' '1.92' '1.91' '1.90' '1.89' '1.88' '1.87'
 '1.86' '1.85' '1.84' '1.83' '1.82' '1.81' '1.80' '1.79' '1.78' '1.77'
 '1.76' '1.75' '1.74' '1.73' '1.72' '1.71' '1.70' '1.69' '1.68' '1.67'
 '1.66' '1.65' '1.64' '1.63' '1.62' '1.61' '1.60' '1.59' '1.58' '1.57'
 '1.56' '1.55' '1.54' '1.53' '1.52' '1.51' '1.50' '1.49' '1.48' '1.47'
 '1.46' '1.45' '1.44' '1.43' '1.42' '1.41' '1.40' '1.39' '1.38' '1.37'
 '1.36' '1.35' '1.34' '1.33' '1.32' '1.31' '1.30' '1.29' '1.28' '1.27'
 '1.26' '1.25' '1.24' '1.23' '1.22' '1.21' '1.20' '1.19' '1.18' '1.17'
 '1.16' '1.15' '1.14' '1.13' '1.12' '1.11' '1.10' '1.09' '1.08' '1.07'
 '1.06' '1.05' '1.04' '1.03' '1.02' '1.01' '1.00' '0.99' '0.98' '0.97'
 '0.96' '0.95' '0.94' '0.93' '0.92' '0.91' '0.90' '0.89' '0.88' '0.87'
 '0.86' '0.85' '0.84' '0.83' '0.82' '0.81' '0.80' '0.79' '0.78' '0.77'
 '0.76' '0.75' '0.74' '0.73' '0.72' '0.71' '0.70' '0.69' '0.68' '0.67'
 '0.66' '0.65' '0.64' '0.63' '0.62' '0.61' '0.60' '0.59' '0.58' '0.57'
 '0.56' '0.55' '0.54' '0.53' '0.52' '0.51' '0.50' '0.49' '0.48' '0.47'
 '0.46' '0.45' '0.44' '0.43' '0.42' '0.41' '0.40' '0.39' '0.38' '0.37'
 '0.36' '0.35' '0.34' '0.33' '0.32' '0.31' '0.30' '0.29' '0.28' '0.27'
 '0.26' '0.25' '0.24' '0.23' '0.22' '0.21' '0.20' '0.19' '0.18' '0.17'
 '0.16' '0.15' '0.14' '0.13' '0.12' '0.11' '0.10' '0.09' '0.08' '0.07'
 '0.06' '0.05' '0.04' '0.03' '0.02' '0.01']
 ****************************************************************************************************

In [139]:
# Repair 'user_score' column: replace the 'tbd' to NaN value then convert the data type from object into float. 
df['user_score']= df['user_score'].replace('tbd',np.nan) 
df['user_score']= df['user_score'].astype(float)  
df['user_score'].dtype

dtype('float64')

#### Fill the Missing Values:

In [140]:
cols_tobe_filled_num=['user_score','year_of_release']  # fill by mean or median based on the outliers calculation or check box plot.
cols_tobe_filled_cat=['rating','developer','publisher','name','genre']   # Fill missing values by mode, or label as "Unknown" based on histogram.

Calculate the outliers to fill the numericall columns

In [141]:
def outlier_percentage(series):
    series = series.dropna()
    
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = series[(series < lower_bound) | (series > upper_bound)]
    
    return round(len(outliers) / len(series) * 100, 2)

fill=['user_score','year_of_release']

outlier_report = {
    col: outlier_percentage(df[col])
    for col in fill
}


print(f'outlier_report: {outlier_report}')

outlier_report: {'user_score': 4.02, 'year_of_release': 1.85}

In [142]:
for col in fill:
    fig_box= px.box(df,x=col, title=f"box plot of {col}")
    fig_box.show()

In [199]:
# Fill the numericall missing values by median based on calculation and box plot.
df['year_of_release'].fillna(df['year_of_release'].median(),inplace=True)  
df['user_score'].fillna(df['user_score'].median(),inplace=True) 

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               16719 non-null  string
 1   platform           16719 non-null  string
 2   year_of_release    16719 non-null  Int64
 3   genre              16719 non-null  string
 4   publisher          16719 non-null  string
 5   na_sales           16719 non-null  string
 6   eu_sales           16719 non-null  string
 7   jp_sales           16719 non-null  string
 8   other_sales        16719 non-null  string
 9   global_sales       16719 non-null  float64
 10  user_score         16719 non-null  float64
 11  developer          16719 non-null  string
 12  rating             16719 non-null  string
 13  sales_category     16719 non-null  string
 14  game_age           16719 non-null  Int64
 15  game_age_category  16719 non-null  string
dtypes: Int64(2), float64(2), string(12)
memory usage: 2.7 MB

C:\Users\DELL\AppData\Local\Temp\ipykernel_26532\389642931.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['year_of_release'].fillna(df['year_of_release'].median(),inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_26532\389642931.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['user_score'].fillna(df['user_score'].median(),inplace=True)

In [200]:
cols_tobe_filled_cat=['name','rating','developer','publisher','genre']   # fill by mode or Check the histogram for better insight.

In [145]:
for col in cols_tobe_filled_cat:
    mode_value = df[col].mode()[0]   # to get most frequent value

In [201]:

for col in cols_tobe_filled_cat:
    # Get top 10 categories by frequency
    top10 = df[col].value_counts().nlargest(10).index
    
    # Filter dataframe to only those top 10 categories
    filtered = df[df[col].isin(top10)]
    
    # Plot histogram
    fig_hist = px.histogram(
        filtered,
        x=col,
        title=f"Top 10 Distribution of {col}",
        template="plotly_white"
    )
    fig_hist.show()

In [202]:
cols_tobe_filled_mode=['rating','genre']
cols_tobe_filled_unknown=['name','developer','publisher']

In [203]:
for col in cols_tobe_filled_mode:
    mode_value = df[col].mode()[0]   # to get most frequent value
    df[col].fillna(mode_value, inplace=True)  # then fill it

# Verify no missing values remain.
df[cols_tobe_filled_mode].isna().sum().sort_values(ascending=False)

C:\Users\DELL\AppData\Local\Temp\ipykernel_26532\3809726600.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_value, inplace=True)  # then fill it

rating    0
genre     0
dtype: int64

In [204]:
for col in cols_tobe_filled_unknown:
    df[col].fillna('unknown', inplace=True)  # then fill it

# Verify no missing values remain.
df[cols_tobe_filled_unknown].isna().sum().sort_values(ascending=False)

C:\Users\DELL\AppData\Local\Temp\ipykernel_26532\315697173.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna('unknown', inplace=True)  # then fill it

name         0
developer    0
publisher    0
dtype: int64

In [205]:
df.head()

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,user_score,developer,rating,sales_category,game_age,game_age_category
0,Wii Sports,Wii,2006,Sports,nintendo,41.36,28.96,3.77,8.45,82.53,8.0,Nintendo,E,best_seller,20,old
1,Super Mario Bros.,NES,1985,Platform,nintendo,29.08,3.58,6.81,0.77,40.24,7.5,unknown,E,medium,41,old
2,Mario Kart Wii,Wii,2008,Racing,nintendo,15.68,12.76,3.79,3.29,35.52,8.3,Nintendo,E,medium,18,old
3,Wii Sports Resort,Wii,2009,Sports,nintendo,15.61,10.93,3.28,2.95,32.77,8.0,Nintendo,E,medium,17,old
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,nintendo,11.27,8.89,10.22,1.00,31.37,7.5,unknown,E,medium,30,old

#### Additional Features to Enhance Understanding and better explanation
###### Sales Category: Define a function to categorize sales and apply it in the existing global_sales to create a new feature named sales_category.
###### Game Age Category: Calulate game age and define a function to categorize game age is it new, recent, old or classic.

In [206]:
# Sales Category

df['global_sales'] = pd.to_numeric(df['global_sales'], errors='coerce')   # to ensure global_sales is numeric

def categorize_sales(value):
    
    if 0 <= value < 25:
        return 'low'
    elif 25 <= value < 50:
        return 'medium'
    elif 50 <= value < 75:
        return 'high'
    elif 75 <= value <= 100:
        return 'best_seller'
    else:
        return 'out_of_range'  # optional for values > 100

# Apply the function to create a new column
df['sales_category'] = df['global_sales'].apply(categorize_sales)

print(df[['name','global_sales','sales_category']].head())

                       name  global_sales sales_category
0                Wii Sports         82.53    best_seller
1         Super Mario Bros.         40.24         medium
2            Mario Kart Wii         35.52         medium
3         Wii Sports Resort         32.77         medium
4  Pokemon Red/Pokemon Blue         31.37         medium

In [207]:
# Game Age Category

current_year= datetime.datetime.now().year
df['game_age']=current_year - df['year_of_release']      # Calulate Gmae age

print(df[['year_of_release','game_age']].head())

   year_of_release  game_age
0             2006        20
1             1985        41
2             2008        18
3             2009        17
4             1996        30

In [208]:
def categorize_age(value):
    
    if value < 5:
        return 'new'
    elif 5 <= value < 15:
        return 'recent'
    else:
        return 'old'
    
       

# Apply the function to create a new column
df['game_age_category'] = df['game_age'].apply(categorize_age)

print(df[['game_age_category','game_age']].head())

  game_age_category  game_age
0               old        20
1               old        41
2               old        18
3               old        17
4               old        30

In [154]:
df.head()

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,user_score,developer,rating,sales_category,game_age,game_age_category
0,Wii Sports,Wii,2006,Sports,nintendo,41.36,28.96,3.77,8.45,82.53,8.0,Nintendo,E,best_seller,20,old
1,Super Mario Bros.,NES,1985,Platform,nintendo,29.08,3.58,6.81,0.77,40.24,7.5,unknown,E,medium,41,old
2,Mario Kart Wii,Wii,2008,Racing,nintendo,15.68,12.76,3.79,3.29,35.52,8.3,Nintendo,E,medium,18,old
3,Wii Sports Resort,Wii,2009,Sports,nintendo,15.61,10.93,3.28,2.95,32.77,8.0,Nintendo,E,medium,17,old
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,nintendo,11.27,8.89,10.22,1.00,31.37,7.5,unknown,E,medium,30,old

#### Validate data quality (after cleaning)

In [209]:
print(df.shape)
df.head()

(16719, 16)

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,user_score,developer,rating,sales_category,game_age,game_age_category
0,Wii Sports,Wii,2006,Sports,nintendo,41.36,28.96,3.77,8.45,82.53,8.0,Nintendo,E,best_seller,20,old
1,Super Mario Bros.,NES,1985,Platform,nintendo,29.08,3.58,6.81,0.77,40.24,7.5,unknown,E,medium,41,old
2,Mario Kart Wii,Wii,2008,Racing,nintendo,15.68,12.76,3.79,3.29,35.52,8.3,Nintendo,E,medium,18,old
3,Wii Sports Resort,Wii,2009,Sports,nintendo,15.61,10.93,3.28,2.95,32.77,8.0,Nintendo,E,medium,17,old
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,nintendo,11.27,8.89,10.22,1.00,31.37,7.5,unknown,E,medium,30,old

In [210]:
df.dtypes

name                 string[python]
platform             string[python]
year_of_release               Int64
genre                string[python]
publisher            string[python]
na_sales             string[python]
eu_sales             string[python]
jp_sales             string[python]
other_sales          string[python]
global_sales                float64
user_score                  float64
developer            string[python]
rating               string[python]
sales_category               object
game_age                      Int64
game_age_category            object
dtype: object

In [211]:
# Verify no missing values remain for all columns in data frame.
df.isna().sum().sort_values(ascending=False)

name                 0
platform             0
year_of_release      0
genre                0
publisher            0
na_sales             0
eu_sales             0
jp_sales             0
other_sales          0
global_sales         0
user_score           0
developer            0
rating               0
sales_category       0
game_age             0
game_age_category    0
dtype: int64

In [212]:
# Final data check: show column names, unique counts, and values
for col in df:
   print(col) 
   print(df[col].nunique())
   print(df[col].unique(), '\n','*'*100)

name
11562
<StringArray>
[                                                 'Wii Sports',
                                           'Super Mario Bros.',
                                              'Mario Kart Wii',
                                           'Wii Sports Resort',
                                    'Pokemon Red/Pokemon Blue',
                                                      'Tetris',
                                       'New Super Mario Bros.',
                                                    'Wii Play',
                                   'New Super Mario Bros. Wii',
                                                   'Duck Hunt',
 ...
                                    'Mezase!! Tsuri Master DS',
 'Eiyuu Densetsu: Sora no Kiseki Material Collection Portable',
                                     'STORM: Frontline Nation',
                                            'Strawberry Nauts',
                                                    'Plushees',
                                                     '15 Days',
                                            'Aiyoku no Eustia',
                          'Woody Woodpecker in Crazy Castle 5',
                                            'LMA Manager 2007',
                                     'Haitaka no Psychedelica']
Length: 11562, dtype: string
 ****************************************************************************************************
platform
31
<StringArray>
[ 'Wii',  'NES',   'GB',   'DS', 'X360',  'PS3',  'PS2', 'SNES',  'GBA',
  'PS4',  '3DS',  'N64',   'PS',   'XB',   'PC', '2600',  'PSP', 'XOne',
 'WiiU',   'GC',  'GEN',   'DC',  'PSV',  'SAT',  'SCD',   'WS',   'NG',
 'TG16',  '3DO',   'GG', 'PCFX']
Length: 31, dtype: string
 ****************************************************************************************************
year_of_release
39
<IntegerArray>
[2006, 1985, 2008, 2009, 1996, 1989, 1984, 2005, 1999, 2007, 2010, 2013, 2004,
 1990, 1988, 2002, 2001, 2011, 1998, 2015, 2012, 2014, 1992, 1997, 1993, 1994,
 1982, 2016, 2003, 1986, 2000, 1995, 1991, 1981, 1987, 1980, 1983, 2020, 2017]
Length: 39, dtype: Int64
 ****************************************************************************************************
genre
12
<StringArray>
[      'Sports',     'Platform',       'Racing', 'Role-Playing',
       'Puzzle',         'Misc',      'Shooter',   'Simulation',
       'Action',     'Fighting',    'Adventure',     'Strategy']
Length: 12, dtype: string
 ****************************************************************************************************
publisher
580
<StringArray>
[                   'nintendo',      'microsoft game studios',
        'take two interactive', 'sony computer entertainment',
                  'activision',                     'ubisoft',
          'bethesda softworks',             'electronic arts',
                        'sega',                  'squaresoft',
 ...
                      'piacci',         'paradox development',
                     'otomate',       'ascaron entertainment',
                   'ongakukan',                    'commseed',
           'uig entertainment',                      'takuyo',
          'interchannel holon',                'red flagship']
Length: 580, dtype: string
 ****************************************************************************************************
na_sales
402
<StringArray>
['41.36', '29.08', '15.68', '15.61', '11.27', '23.20', '11.28', '13.96',
 '14.44', '26.93',
 ...
  '0.54',  '0.04',  '0.17',  '0.44',  '0.03',  '0.33',  '0.31',  '0.40',
  '0.21',  '0.19']
Length: 402, dtype: string
 ****************************************************************************************************
eu_sales
307
<StringArray>
['28.96',  '3.58', '12.76', '10.93',  '8.89',  '2.26',  '9.14',  '9.18',
  '6.94',  '0.63',
 ...
  '0.06',  '0.03',  '0.37',  '0.05',  '0.23',  '0.65',  '0.42',  '0.34',
  '0.35',  '0.78']
Length: 307, dtype: string
 ****************************************************************************************************
jp_sales
244
<StringArray>
[ '3.77',  '6.81',  '3.79',  '3.28', '10.22',  '4.22',  '6.50',  '2.93',
  '4.70',  '0.28',
 ...
  '1.26',  '0.85',  '0.43',  '0.67',  '1.14',  '0.86',  '1.17',  '0.50',
  '1.02',  '0.97']
Length: 244, dtype: string
 ****************************************************************************************************
other_sales
155
<StringArray>
['8.45', '0.77', '3.29', '2.95', '1.00', '0.58', '2.88', '2.84', '2.24',
 '0.47',
 ...
 '0.01', '2.46', '0.03', '1.51', '2.05', '1.68', '1.82', '1.33', '0.94',
 '0.93']
Length: 155, dtype: string
 ****************************************************************************************************
global_sales
629
[8.253e+01 4.024e+01 3.552e+01 3.277e+01 3.137e+01 3.026e+01 2.980e+01
 2.892e+01 2.832e+01 2.831e+01 2.467e+01 2.321e+01 2.310e+01 2.270e+01
 2.181e+01 2.179e+01 2.104e+01 2.081e+01 2.061e+01 2.015e+01 1.825e+01
 1.814e+01 1.728e+01 1.627e+01 1.615e+01 1.585e+01 1.529e+01 1.514e+01
 1.498e+01 1.473e+01 1.464e+01 1.463e+01 1.461e+01 1.460e+01 1.379e+01
 1.367e+01 1.347e+01 1.332e+01 1.310e+01 1.284e+01 1.266e+01 1.263e+01
 1.261e+01 1.213e+01 1.212e+01 1.189e+01 1.177e+01 1.168e+01 1.166e+01
 1.135e+01 1.118e+01 1.101e+01 1.095e+01 1.081e+01 1.070e+01 1.060e+01
 1.055e+01 1.050e+01 1.049e+01 1.030e+01 1.025e+01 1.012e+01 9.900e+00
 9.870e+00 9.860e+00 9.720e+00 9.710e+00 9.490e+00 9.440e+00 9.360e+00
 9.310e+00 9.300e+00 9.180e+00 9.160e+00 8.910e+00 8.790e+00 8.760e+00
 8.570e+00 8.490e+00 8.380e+00 8.270e+00 8.160e+00 8.090e+00 8.070e+00
 8.050e+00 8.010e+00 7.990e+00 7.980e+00 7.860e+00 7.810e+00 7.720e+00
 7.690e+00 7.660e+00 7.600e+00 7.590e+00 7.580e+00 7.550e+00 7.510e+00
 7.460e+00 7.390e+00 7.380e+00 7.320e+00 7.200e+00 7.170e+00 7.160e+00
 7.150e+00 7.140e+00 7.130e+00 7.090e+00 7.070e+00 6.950e+00 6.900e+00
 6.830e+00 6.820e+00 6.760e+00 6.750e+00 6.740e+00 6.710e+00 6.680e+00
 6.660e+00 6.650e+00 6.620e+00 6.510e+00 6.490e+00 6.470e+00 6.450e+00
 6.440e+00 6.430e+00 6.410e+00 6.400e+00 6.390e+00 6.340e+00 6.320e+00
 6.310e+00 6.300e+00 6.290e+00 6.270e+00 6.210e+00 6.190e+00 6.090e+00
 6.080e+00 6.050e+00 6.030e+00 5.990e+00 5.950e+00 5.870e+00 5.820e+00
 5.780e+00 5.740e+00 5.640e+00 5.630e+00 5.580e+00 5.550e+00 5.540e+00
 5.490e+00 5.480e+00 5.470e+00 5.460e+00 5.450e+00 5.420e+00 5.390e+00
 5.380e+00 5.340e+00 5.330e+00 5.310e+00 5.300e+00 5.290e+00 5.270e+00
 5.260e+00 5.240e+00 5.230e+00 5.220e+00 5.210e+00 5.200e+00 5.190e+00
 5.160e+00 5.150e+00 5.140e+00 5.130e+00 5.120e+00 5.100e+00 5.090e+00
 5.080e+00 5.070e+00 5.050e+00 5.030e+00 5.020e+00 5.010e+00 5.000e+00
 4.980e+00 4.930e+00 4.920e+00 4.910e+00 4.880e+00 4.870e+00 4.850e+00
 4.840e+00 4.820e+00 4.800e+00 4.790e+00 4.760e+00 4.730e+00 4.710e+00
 4.700e+00 4.680e+00 4.670e+00 4.630e+00 4.620e+00 4.610e+00 4.600e+00
 4.590e+00 4.570e+00 4.530e+00 4.500e+00 4.490e+00 4.480e+00 4.470e+00
 4.460e+00 4.450e+00 4.430e+00 4.420e+00 4.410e+00 4.390e+00 4.380e+00
 4.370e+00 4.360e+00 4.340e+00 4.330e+00 4.320e+00 4.310e+00 4.290e+00
 4.280e+00 4.270e+00 4.240e+00 4.230e+00 4.220e+00 4.210e+00 4.200e+00
 4.190e+00 4.180e+00 4.170e+00 4.160e+00 4.140e+00 4.120e+00 4.110e+00
 4.100e+00 4.090e+00 4.080e+00 4.070e+00 4.060e+00 4.050e+00 4.040e+00
 4.030e+00 4.010e+00 3.980e+00 3.970e+00 3.960e+00 3.950e+00 3.940e+00
 3.910e+00 3.900e+00 3.890e+00 3.880e+00 3.870e+00 3.850e+00 3.840e+00
 3.830e+00 3.800e+00 3.790e+00 3.770e+00 3.760e+00 3.740e+00 3.730e+00
 3.720e+00 3.710e+00 3.700e+00 3.670e+00 3.660e+00 3.650e+00 3.640e+00
 3.630e+00 3.620e+00 3.610e+00 3.600e+00 3.590e+00 3.580e+00 3.560e+00
 3.540e+00 3.530e+00 3.520e+00 3.510e+00 3.500e+00 3.490e+00 3.480e+00
 3.470e+00 3.460e+00 3.450e+00 3.440e+00 3.420e+00 3.410e+00 3.400e+00
 3.390e+00 3.380e+00 3.370e+00 3.360e+00 3.350e+00 3.340e+00 3.330e+00
 3.320e+00 3.310e+00 3.300e+00 3.280e+00 3.270e+00 3.260e+00 3.250e+00
 3.240e+00 3.230e+00 3.210e+00 3.200e+00 3.190e+00 3.180e+00 3.170e+00
 3.150e+00 3.140e+00 3.130e+00 3.120e+00 3.110e+00 3.100e+00 3.090e+00
 3.080e+00 3.070e+00 3.060e+00 3.050e+00 3.040e+00 3.030e+00 3.020e+00
 3.010e+00 3.000e+00 2.990e+00 2.960e+00 2.950e+00 2.940e+00 2.930e+00
 2.920e+00 2.910e+00 2.900e+00 2.890e+00 2.880e+00 2.870e+00 2.860e+00
 2.850e+00 2.840e+00 2.830e+00 2.820e+00 2.810e+00 2.800e+00 2.790e+00
 2.780e+00 2.770e+00 2.760e+00 2.750e+00 2.730e+00 2.710e+00 2.700e+00
 2.690e+00 2.680e+00 2.670e+00 2.660e+00 2.650e+00 2.630e+00 2.620e+00
 2.610e+00 2.600e+00 2.590e+00 2.580e+00 2.570e+00 2.560e+00 2.540e+00
 2.530e+00 2.520e+00 2.500e+00 2.490e+00 2.480e+00 2.470e+00 2.460e+00
 2.450e+00 2.440e+00 2.430e+00 2.420e+00 2.410e+00 2.400e+00 2.390e+00
 2.380e+00 2.370e+00 2.360e+00 2.350e+00 2.340e+00 2.320e+00 2.310e+00
 2.300e+00 2.290e+00 2.280e+00 2.270e+00 2.260e+00 2.250e+00 2.240e+00
 2.230e+00 2.220e+00 2.210e+00 2.200e+00 2.190e+00 2.180e+00 2.170e+00
 2.160e+00 2.150e+00 2.140e+00 2.130e+00 2.120e+00 2.110e+00 2.100e+00
 2.090e+00 2.080e+00 2.070e+00 2.060e+00 2.050e+00 2.040e+00 2.030e+00
 2.020e+00 2.010e+00 2.000e+00 1.990e+00 1.980e+00 1.970e+00 1.960e+00
 1.950e+00 1.940e+00 1.930e+00 1.920e+00 1.910e+00 1.900e+00 1.890e+00
 1.880e+00 1.870e+00 1.860e+00 1.850e+00 1.840e+00 1.830e+00 1.820e+00
 1.810e+00 1.800e+00 1.790e+00 1.780e+00 1.770e+00 1.760e+00 1.750e+00
 1.740e+00 1.730e+00 1.720e+00 1.710e+00 1.700e+00 1.690e+00 1.680e+00
 1.670e+00 1.660e+00 1.650e+00 1.640e+00 1.630e+00 1.620e+00 1.610e+00
 1.600e+00 1.590e+00 1.580e+00 1.570e+00 1.560e+00 1.550e+00 1.540e+00
 1.530e+00 1.520e+00 1.510e+00 1.500e+00 1.490e+00 1.480e+00 1.470e+00
 1.460e+00 1.450e+00 1.440e+00 1.430e+00 1.420e+00 1.410e+00 1.400e+00
 1.390e+00 1.380e+00 1.370e+00 1.360e+00 1.350e+00 1.340e+00 1.330e+00
 1.320e+00 1.310e+00 1.300e+00 1.290e+00 1.280e+00 1.270e+00 1.260e+00
 1.250e+00 1.240e+00 1.230e+00 1.220e+00 1.210e+00 1.200e+00 1.190e+00
 1.180e+00 1.170e+00 1.160e+00 1.150e+00 1.140e+00 1.130e+00 1.120e+00
 1.110e+00 1.100e+00 1.090e+00 1.080e+00 1.070e+00 1.060e+00 1.050e+00
 1.040e+00 1.030e+00 1.020e+00 1.010e+00 1.000e+00 9.900e-01 9.800e-01
 9.700e-01 9.600e-01 9.500e-01 9.400e-01 9.300e-01 9.200e-01 9.100e-01
 9.000e-01 8.900e-01 8.800e-01 8.700e-01 8.600e-01 8.500e-01 8.400e-01
 8.300e-01 8.200e-01 8.100e-01 8.000e-01 7.900e-01 7.800e-01 7.700e-01
 7.600e-01 7.500e-01 7.400e-01 7.300e-01 7.200e-01 7.100e-01 7.000e-01
 6.900e-01 6.800e-01 6.700e-01 6.600e-01 6.500e-01 6.400e-01 6.300e-01
 6.200e-01 6.100e-01 6.000e-01 5.900e-01 5.800e-01 5.700e-01 5.600e-01
 5.500e-01 5.400e-01 5.300e-01 5.200e-01 5.100e-01 5.000e-01 4.900e-01
 4.800e-01 4.700e-01 4.600e-01 4.500e-01 4.400e-01 4.300e-01 4.200e-01
 4.100e-01 4.000e-01 3.900e-01 3.800e-01 3.700e-01 3.600e-01 3.500e-01
 3.400e-01 3.300e-01 3.200e-01 3.100e-01 3.000e-01 2.900e-01 2.800e-01
 2.700e-01 2.600e-01 2.500e-01 2.400e-01 2.300e-01 2.200e-01 2.100e-01
 2.000e-01 1.900e-01 1.800e-01 1.700e-01 1.600e-01 1.500e-01 1.400e-01
 1.300e-01 1.200e-01 1.100e-01 1.000e-01 9.000e-02 8.000e-02 7.000e-02
 6.000e-02 5.000e-02 4.000e-02 3.000e-02 2.000e-02 1.000e-02]
 ****************************************************************************************************
user_score
95
[8.  7.5 8.3 8.5 6.6 8.4 8.6 7.7 6.3 7.4 8.2 9.  7.9 8.1 8.7 7.1 3.4 5.3
 4.8 3.2 8.9 6.4 7.8 2.6 7.2 9.2 7.  7.3 4.3 7.6 5.7 5.  9.1 6.5 8.8 6.9
 9.4 6.8 6.1 6.7 5.4 4.  4.9 4.5 9.3 6.2 4.2 6.  3.7 4.1 5.8 5.6 5.5 4.4
 4.6 5.9 3.9 3.1 2.9 5.2 3.3 4.7 5.1 3.5 2.5 1.9 3.  2.7 2.2 2.  9.5 2.1
 3.6 2.8 1.8 3.8 0.  1.6 9.6 2.4 1.7 1.1 0.3 1.5 0.7 1.2 2.3 0.5 1.3 0.2
 0.6 1.4 0.9 1.  9.7]
 ****************************************************************************************************
developer
1697
<StringArray>
[                                 'Nintendo',
                                   'unknown',
                       'Good Science Studio',
                            'Rockstar North',
                         'Polyphony Digital',
         'Infinity Ward, Sledgehammer Games',
                                  'Treyarch',
                             'Infinity Ward',
                                'DMA Design',
                                 'Game Arts',
 ...
                               'React Games',
       'Bigben Interactive, Red Wagon Games',
                                   'Papyrus',
                             'Inferno Games',
                       'Katauri Interactive',
 'High Moon Studios, Mercenary Technologies',
                'Infinite Dreams, Paragon 5',
                          'Big Red Software',
                              'Atomic Games',
                        'Interchannel-Holon']
Length: 1697, dtype: string
 ****************************************************************************************************
rating
8
<StringArray>
['E', 'M', 'T', 'E10+', 'K-A', 'AO', 'EC', 'RP']
Length: 8, dtype: string
 ****************************************************************************************************
sales_category
3
['best_seller' 'medium' 'low']
 ****************************************************************************************************
game_age
39
<IntegerArray>
[20, 41, 18, 17, 30, 37, 42, 21, 27, 19, 16, 13, 22, 36, 38, 24, 25, 15, 28,
 11, 14, 12, 34, 29, 33, 32, 44, 10, 23, 40, 26, 31, 35, 45, 39, 46, 43,  6,
  9]
Length: 39, dtype: Int64
 ****************************************************************************************************
game_age_category
2
['old' 'recent']
 ****************************************************************************************************

### Export cleaned DataFrame to CSV for EDA.

In [233]:
# Save the cleaned df to a new CSV file named 'cleaned_games.csv'
df.to_csv('clean_video_games.csv', index=False)

In [234]:
cleaned_df= pd.read_csv('clean_video_games.csv')
cleaned_df.head()

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,user_score,developer,rating,sales_category,game_age,game_age_category
0,Wii Sports,Wii,2006,Sports,nintendo,41.36,28.96,3.77,8.45,82.53,8.0,Nintendo,E,best_seller,20,old
1,Super Mario Bros.,NES,1985,Platform,nintendo,29.08,3.58,6.81,0.77,40.24,7.5,unknown,E,medium,41,old
2,Mario Kart Wii,Wii,2008,Racing,nintendo,15.68,12.76,3.79,3.29,35.52,8.3,Nintendo,E,medium,18,old
3,Wii Sports Resort,Wii,2009,Sports,nintendo,15.61,10.93,3.28,2.95,32.77,8.0,Nintendo,E,medium,17,old
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,nintendo,11.27,8.89,10.22,1.00,31.37,7.5,unknown,E,medium,30,old

## Exploratory Data Analysis (EDA)

### Sales Performance Insights ...

##### Top-Selling Games:

In [215]:
# Top selling game: identify the game with highet global_sales.
cleaned_df['global_sales'].max()
df.loc[cleaned_df['global_sales'].idxmax()]['name']

'Wii Sports'

In [235]:
top5games= cleaned_df['name'].value_counts().head(5)
top5games

name
Need for Speed: Most Wanted    14
Ratatouille                     9
Madden NFL 07                   9
FIFA 14                         9
LEGO Marvel Super Heroes        9
Name: count, dtype: int64

In [217]:
# Bar Chart - Top 10 Games with the Globa_sales. 
top10_games = cleaned_df[['name','global_sales','genre']].sort_values(by='global_sales', ascending=False).head(10)
top10_games

                        name  global_sales         genre
0                 Wii Sports         82.53        Sports
1          Super Mario Bros.         40.24      Platform
2             Mario Kart Wii         35.52        Racing
3          Wii Sports Resort         32.77        Sports
4   Pokemon Red/Pokemon Blue         31.37  Role-Playing
5                     Tetris         30.26        Puzzle
6      New Super Mario Bros.         29.80      Platform
7                   Wii Play         28.92          Misc
8  New Super Mario Bros. Wii         28.32      Platform
9                  Duck Hunt         28.31       Shooter

In [218]:

#my_colors = ["#4B0082", "#9B59B6", "#00A86B", "#2ECC71", "#2C2C2C", "#BDC3C7"]

fig_top10_games = px.bar(
    top10_games,
    x='name',
    y='global_sales',
    title='Top 10 Games by Global Sales (Bar Chart)',
    text='global_sales',
    color='genre'  ,
   # color_discrete_sequence=my_colors
)

fig_top10_games.update_layout(
    xaxis_title="Game Names",
    yaxis_title="Global Sales (Millions)"
)

fig_top10_games.update_traces(texttemplate='%{text:.2f}', textposition='outside')
fig_top10_games.show()

In [219]:
# Top 10 best‑selling games list (based in global sales) with age rating.
best_sellinggame_with_agerate = cleaned_df.sort_values(by='global_sales', ascending=False).head(10)

print(best_sellinggame_with_agerate[['name','rating']])

                        name rating
0                 Wii Sports      E
1          Super Mario Bros.      E
2             Mario Kart Wii      E
3          Wii Sports Resort      E
4   Pokemon Red/Pokemon Blue      E
5                     Tetris      E
6      New Super Mario Bros.      E
7                   Wii Play      E
8  New Super Mario Bros. Wii      E
9                  Duck Hunt      E

In [236]:
# Top 10 games with with age rating

fig_line_top10_games=px.line(best_sellinggame_with_agerate,x='name',y='global_sales',color='rating',title='Top 10 Games by Sales (Line)',text='global_sales')
fig_line_top10_games

In [237]:
# Highest Rated Games
# Sort by user_score and select top 10

# Top 10 best‑selling games list (based in global sales) with age rating.

top_rated = cleaned_df.sort_values(by='user_score', ascending=False).head(10)

print(top_rated[['name','user_score']])

                                        name  user_score
14414                     Breath of Fire III         9.7
8976         Boktai: The Sun is in Your Hand         9.6
3417   Harvest Moon: Friends of Mineral Town         9.6
5920                     MLB SlugFest Loaded         9.5
10106                      Cory in the House         9.5
16631                          Karnaaj Rally         9.5
16550            Wade Hixton's Counter Punch         9.5
1645                Golden Sun: The Lost Age         9.5
11120                Super Puzzle Fighter II         9.5
712      Paper Mario: The Thousand-Year Door         9.4

In [238]:
fig = px.strip(
    top_rated,
    y='user_score',
    x='name',
    title='Top 10 Highest Rated Games (strip)',
    labels={'user_score':'User Score', 'name':'Game Name'},
    template='plotly_white',
    color='genre'
)

fig.update_layout(yaxis={'categoryorder':'total ascending'})
fig.show()

In [239]:
# Top 10 best‑selling games list (based on global sales) with age rating
best_selling_with_age_rate = (
    cleaned_df.groupby(['name', 'rating'])['global_sales'].sum().reset_index().sort_values(by='global_sales', ascending=False)
    .head(10)
)
print(best_selling_with_age_rate[['name', 'rating', 'global_sales']])

                                 name rating  global_sales
11455                      Wii Sports      E         82.53
3859               Grand Theft Auto V      M         56.57
9677                Super Mario Bros.      E         45.31
10082                          Tetris      E         35.84
5782                   Mario Kart Wii      E         35.52
11457               Wii Sports Resort      E         32.77
7611         Pokemon Red/Pokemon Blue      E         31.37
1296   Call of Duty: Modern Warfare 3      M         30.59
1287          Call of Duty: Black Ops      M         30.24
6967            New Super Mario Bros.      E         29.80

In [240]:

fig_best_selling = px.bar(
    best_selling_with_age_rate,
    x="global_sales",
    y="name",
    color="rating",   # color bars by age rating
    orientation="h",  # horizontal bars for readability
    title="Top 10 Best-Selling Games with Age Rating (Bar Chart)",
    labels={"global_sales":"Global Sales (millions)", "name":"Game"},
    template="plotly_white"
)

fig_best_selling.show()

##### Average sales for each region (NA, EU, JP, Other):

In [241]:
# Sales by regions: Compare NA, EU, JP, and Other sales.
regions=['na_sales','eu_sales','jp_sales','other_sales']
region_sales = cleaned_df[['na_sales','eu_sales','jp_sales','other_sales']].mean()
region_sales = region_sales.rename({     # rename region sales columns for clearer labels and better visualization
    'na_sales': 'North America',
    'eu_sales': 'Europe',
    'jp_sales': 'Japan',
    'other_sales': 'Other Regions'
})
region_sales_df = region_sales.reset_index()
region_sales_df.columns = ['Region', 'Average Sales']

print(region_sales_df)

          Region  Average Sales
0  North America       0.263330
1         Europe       0.145025
2          Japan       0.077602
3  Other Regions       0.047332

In [242]:

corr_with_global = cleaned_df[regions].corrwith(cleaned_df['global_sales']).reset_index()
corr_with_global.columns = ['Region', 'Correlation with Global Sales']


corr_with_global['Region'] = corr_with_global['Region'].replace({
    'na_sales': 'North America',
    'eu_sales': 'Europe',
    'jp_sales': 'Japan',
    'other_sales': 'Other Regions'
})

fig = px.bar(corr_with_global, x='Region', y='Correlation with Global Sales',
             title="Correlation of Regional Sales with Global Sales (Bar Chart)",
             color='Correlation with Global Sales', color_continuous_scale=['#4B0082', '#00A86B', '#BDC3C7']) # purple → green → gray)
fig.show()

In [243]:
# Sales by game_name and regions.
pivot = pd.pivot_table(cleaned_df, values=['na_sales','eu_sales','jp_sales','other_sales','global_sales'],index='name',aggfunc='sum')

top10_sales_regions = pivot.sort_values(by='global_sales', ascending=False).head(10)
top10_sales_regions

,eu_sales,global_sales,jp_sales,na_sales,other_sales
name,,,,,
Wii Sports,28.96,82.53,3.77,41.36,8.45
Grand Theft Auto V,23.42,56.57,1.42,23.84,7.90
Super Mario Bros.,4.88,45.31,6.96,32.48,0.99
Tetris,2.95,35.84,6.03,26.17,0.69
Mario Kart Wii,12.76,35.52,3.79,15.68,3.29
Wii Sports Resort,10.93,32.77,3.28,15.61,2.95
Pokemon Red/Pokemon Blue,8.89,31.37,10.22,11.27,1.00
Call of Duty: Black Ops,9.35,30.82,0.59,17.57,3.31
Call of Duty: Modern Warfare 3,11.15,30.59,0.62,15.54,3.29
New Super Mario Bros.,9.14,29.80,6.50,11.28,2.88

##### Sales by Platform:

In [244]:
# Create a pivot table to summarize global sales by platform.
pivot = pd.pivot_table(cleaned_df,values='global_sales', index='platform',aggfunc='sum')
print(pivot)

          global_sales
platform
2600             97.08
3DO               0.10
3DS             259.09
DC               15.97
DS              807.10
GB              255.45
GBA             318.50
GC              199.36
GEN              30.78
GG                0.04
N64             218.88
NES             251.07
NG                1.44
PC              260.30
PCFX              0.03
PS              730.68
PS2            1255.64
PS3             939.43
PS4             314.23
PSP             294.30
PSV              54.12
SAT              33.59
SCD               1.87
SNES            200.05
TG16              0.16
WS                1.42
Wii             908.13
WiiU             82.16
X360            971.63
XB              258.26
XOne            159.44

In [245]:
# Count each rating per each platform
rating_counts = cleaned_df.groupby('platform')['rating'].value_counts().sort_values(ascending=False).head(10)
rating_counts_df = rating_counts.reset_index()

print(rating_counts_df)

  platform rating  count
0       DS      E   1755
1      PS2      E   1236
2       PS      E   1105
3      PSP      E    853
4      Wii      E    821
5      GBA      E    726
6      PS3      E    590
7      PS2      T    576
8     X360      E    457
9      3DS      E    384

In [246]:
pivot = pd.pivot_table(
    cleaned_df,
   
    index='rating',
    columns='platform',   # ratings become columns
    aggfunc='size',     # count occurrences
    fill_value=0
)
pivot

platform,2600,3DO,3DS,DC,DS,GB,GBA,GC,GEN,GG,...,SAT,SCD,SNES,TG16,WS,Wii,WiiU,X360,XB,XOne
rating,,,,,,,,,,,,,,,,,,,,,
AO,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
E,133,3,384,41,1755,98,726,317,29,1,...,173,6,239,2,6,821,77,457,339,106
E10+,0,0,76,0,259,0,25,31,0,0,...,0,0,0,0,0,242,42,168,31,31
EC,0,0,0,0,2,0,0,1,0,0,...,0,0,0,0,0,2,0,0,0,0
K-A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
M,0,0,12,1,10,0,7,38,0,0,...,0,0,0,0,0,33,15,294,161,70
RP,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
T,0,0,48,10,126,0,64,169,0,0,...,0,0,0,0,0,222,13,343,292,40

In [247]:

# Heatmap visualization
fig_heatmap = px.imshow(
    pivot,
    labels=dict(x="Platform", y="Rating", color="Avg Global Sales"),
    title="Average Global Sales by Genre and Platform (Heatmap)",
    color_continuous_scale=[ '#BDC3C7', '#00A86B', '#4B0082']  # gray → green → purple
)
fig_heatmap.show()

In [248]:
# Most Popular platform based on global sales (Wii , GBA , PC, etc...)
platform_sales_top10 = cleaned_df.groupby('platform')['global_sales'].count().sort_values(ascending=False).head(10).reset_index()
print(platform_sales_top10.head(10))

  platform  global_sales
0      PS2          2161
1       DS          2152
2      PS3          1331
3      Wii          1320
4     X360          1262
5      PSP          1209
6       PS          1197
7       PC           974
8       XB           824
9      GBA           822

In [230]:
fig = px.bar(
    platform_sales_top10,
    x='global_sales',
    y='platform',

    title='Top 10 Platforms by Global Sales (Bar Chart)',
    labels={'global_sales':'Global Sales (millions)', 'platform':'Platform'},
    template='plotly_white'
)

fig.show()

##### Sales by Genre:

In [249]:
# Most profitable game genres 
genre_sales = cleaned_df.groupby('genre')['global_sales'].sum().sort_values(ascending=False).head(10)
genre_sales_df = genre_sales.reset_index()
print(genre_sales_df)

          genre  global_sales
0        Action       1747.69
1        Sports       1332.00
2       Shooter       1052.94
3  Role-Playing        934.40
4      Platform        828.08
5          Misc        803.18
6        Racing        728.90
7      Fighting        447.48
8    Simulation        390.42
9        Puzzle        243.02

In [250]:
fig = px.scatter(
    genre_sales_df,
    x="genre",
    y="global_sales",
    size="global_sales",       # bubble size reflects sales
    color="genre",             # color by genre, it's optional
    title="Top 10 Most Profitable Game Genres (Scatter/Bubble)",
    labels={"global_sales":"Global Sales (millions)", "genre":"Genre"},
    template="plotly_white",
    trendline="ols" 
       
)

fig.show()

In [251]:
# Count frequency of each genre
genre_count = cleaned_df['genre'].value_counts(ascending=False).reset_index()
genre_count

           genre  count
0         Action   3372
1         Sports   2348
2           Misc   1750
3   Role-Playing   1500
4        Shooter   1323
5      Adventure   1303
6         Racing   1249
7       Platform    888
8     Simulation    874
9       Fighting    849
10      Strategy    683
11        Puzzle    580

In [252]:
genre_count = cleaned_df['genre'].value_counts().reset_index()
genre_count.columns = ['genre', 'frequency']

# Create pie chart for top 10 genres
ffig_top10genres = px.pie(
    genre_count.head(10), 
    values='frequency', 
    names='genre', 
    title="Top 10 Genres Distribution (Pie Chart)",
    color_discrete_sequence=my_colors   # <-- apply your palette here

)
ffig_top10genres

In [253]:
top10_profitable_game = (
    cleaned_df.groupby(['genre','game_age_category'])['global_sales']
    .mean()
    .reset_index()
    .sort_values(by='global_sales', ascending=False)
    .head(10)
)

fig = px.bar(
    top10_profitable_game,
    x='game_age_category',
    y='global_sales',
    color='game_age_category',
    title="Top 10 Most Profitable Game Genres (Bar Chart)",
    labels={'global_sales':'Average Global Sales (millions)', 'genre':'Genre','game_age_category':'G_Age_Cat'},
    template='plotly_white',facet_col='genre'
)

fig.show()

##### Game names by user_score:

In [254]:
top10_gamesbyuser_score=df[['user_score','genre']].sort_values(by='user_score',ascending=False).head(10)
top10_gamesbyuser_score

       user_score         genre
14414         9.7  Role-Playing
8976          9.6  Role-Playing
3417          9.6    Simulation
5920          9.5        Sports
10106         9.5        Action
16631         9.5        Racing
16550         9.5        Sports
1645          9.5  Role-Playing
11120         9.5        Puzzle
712           9.4  Role-Playing

In [255]:
fig_bar_game_userscore=px.bar(top10_gamesbyuser_score,x='genre',y='user_score', 
                               title='Top 10 User score by Game Genre (Bar Chart)' , 
                              labels={'user_score':'User Score','genre': 'Genre'}, color_discrete_sequence=my_colors )
fig_bar_game_userscore

In [256]:
# Relationship between user scores and global sales for the top 10 games, with bubbles sized by sales and colored by genre
top10_score_sales = (
    cleaned_df.sort_values(by="user_score", ascending=False)
    .head(10)
)

# Scatter bubble chart with trendline
fig_score_sales_top10 = px.scatter(
    top10_score_sales,
    x="user_score",
    y="global_sales",
    size="global_sales",   # bubble size reflects sales
    color="genre",
    hover_name="name",     # show game name on hover
    title="Top 10 Games by User Score vs Global Sales (with Trendline)",
    labels={"user_score":"User Score", "global_sales":"Global Sales (millions)"},
    template="plotly_white",
    trendline="ols"        # regression line
)

fig_score_sales_top10.show()

##### Sales by Publisher:

In [257]:
# Top performing publishers
publisher_sales= cleaned_df.groupby('publisher')['global_sales'].count().sort_values(ascending=False)
print(publisher_sales.head())

publisher
electronic arts                 1356
activision                       985
namco bandai games               939
ubisoft                          933
konami digital entertainment     834
Name: global_sales, dtype: int64

In [189]:
fig_publisher_sales = px.bar(
    publisher_sales.head(5).reset_index(),
    x='global_sales',
    y='publisher',
    orientation='h',
    title='Top 10 Publishers by Global Sales (Bar Chart)',
    labels={'global_sales':'Global Sales (millions)', 'publisher':'Publisher'},
    template='plotly_white'
)
fig_publisher_sales

##### Yearly Sales Trends:

In [258]:
# See how game sales change over time.

years_sales=cleaned_df.groupby('year_of_release')['global_sales'].sum().sort_values(ascending=False)
print(years_sales.head())

year_of_release
2007    704.33
2008    671.79
2009    658.88
2010    590.59
2006    518.22
Name: global_sales, dtype: float64

In [191]:
# Line Chart of Sales Over Year Time 

fig_line_sales_year = px.line(
    cleaned_df.groupby('year_of_release')['global_sales'].sum().reset_index(),
    x='year_of_release',
    y='global_sales',
    title='Global Sales Over Time (Line Chart)',
    labels={'year_of_release':'Year of Release', 'global_sales':'Global Sales (millions)'},
    template='plotly_white', 
   
)

fig_line_sales_year.show()

Number of Games Released per Year

In [259]:
games_per_year=cleaned_df.groupby('year_of_release')['name'].count().reset_index().sort_values(by='name', ascending=False).rename(columns={'name':'game_count'})
games_per_year

    year_of_release  game_count
27             2007        1466
28             2008        1427
29             2009        1426
30             2010        1255
31             2011        1136
26             2006        1006
25             2005         939
22             2002         829
23             2003         775
24             2004         762
32             2012         653
35             2015         606
34             2014         581
33             2013         544
36             2016         502
21             2001         482
18             1998         379
20             2000         350
19             1999         338
17             1997         289
16             1996         263
15             1995         219
14             1994         121
13             1993          62
1              1981          46
12             1992          43
11             1991          41
2              1982          36
6              1986          21
9              1989          17
3              1983          17
10             1990          16
7              1987          16
8              1988          15
4              1984          14
5              1985          14
0              1980           9
37             2017           3
38             2020           1

In [260]:
# Scatter plot - Number of Games Released per Year
fig = px.scatter(
    games_per_year,
    x='year_of_release',
    y='game_count',
    trendline='ols',   # add regression line
    title="Number of Games Released per Year with Trendline",
    labels={'year_of_release':'Year of Release', 'game_count':'Number of Games'},
    template='plotly_white'
)

fig.show()

In [261]:
# Genre vs Platform pivot table
genre_platform_sales = cleaned_df.pivot_table(
    index='genre',
    columns='platform',
    values='global_sales',
    aggfunc='mean'
)
genre_platform_sales

platform,2600,3DO,3DS,DC,DS,GB,GBA,GC,GEN,GG,...,SAT,SCD,SNES,TG16,WS,Wii,WiiU,X360,XB,XOne
genre,,,,,,,,,,,,,,,,,,,,,
Action,0.480984,NaN,0.310266,0.420000,0.331471,1.320000,0.333892,0.374653,1.032000,NaN,...,0.216667,NaN,0.840000,NaN,NaN,0.483165,0.297656,0.742074,0.317935,0.439412
Adventure,0.850000,0.06,0.128947,0.227273,0.192857,3.432000,0.386316,0.296500,0.095000,NaN,...,0.160000,NaN,0.375000,0.14,NaN,0.214819,0.053333,0.311250,0.117692,0.192143
Fighting,0.620000,NaN,0.755000,0.152500,0.197500,NaN,0.183043,0.438810,1.180000,NaN,...,0.274839,NaN,1.078000,NaN,NaN,0.556190,1.254000,0.574462,0.282292,0.344286
Misc,0.716000,NaN,0.203333,NaN,0.347110,1.668750,0.329545,0.464722,0.030000,NaN,...,0.080000,0.05,0.295294,NaN,NaN,0.772750,0.566818,0.720787,0.208261,0.391579
Platform,1.474444,NaN,1.161429,1.270000,0.834286,2.890000,0.551408,0.392603,2.207143,0.04,...,0.152000,1.50,2.525000,NaN,NaN,1.533103,1.267059,0.452800,0.197143,0.188000
Puzzle,1.334545,0.02,0.277500,NaN,0.350508,3.164667,0.315122,0.361538,NaN,NaN,...,0.200000,NaN,0.490769,NaN,NaN,0.279455,0.330000,0.121429,0.060000,NaN
Racing,0.485000,NaN,1.358182,0.441667,0.568657,2.275000,0.293750,0.347460,0.260000,NaN,...,0.300000,0.07,1.498889,NaN,NaN,0.647849,2.623333,0.625000,0.256016,0.489500
Role-Playing,NaN,NaN,0.957841,0.170000,0.622200,4.201905,0.879589,0.487037,0.090000,NaN,...,0.221176,0.06,0.728600,NaN,0.305,0.391429,0.412857,0.950800,0.587391,0.753571
Shooter,1.103333,NaN,0.184286,0.110000,0.188571,1.200000,0.090000,0.283958,0.130000,NaN,...,0.180909,NaN,0.607000,0.02,NaN,0.433077,0.597000,1.364433,0.481439,1.589211
Simulation,0.450000,0.02,0.884839,0.520000,0.458768,0.710000,0.328333,0.715833,NaN,NaN,...,0.161429,NaN,0.625556,NaN,NaN,0.414138,0.200000,0.354500,0.296250,0.172500
Sports,0.285833,NaN,0.238077,0.366000,0.212230,1.005556,0.186477,0.231727,1.066667,NaN,...,0.174375,NaN,0.364694,NaN,NaN,1.110038,0.398750,0.638018,0.319235,0.704474
Strategy,NaN,NaN,0.140000,NaN,0.188228,1.150000,0.413889,0.392727,0.190000,NaN,...,0.180000,0.14,0.332000,NaN,0.100,0.201200,0.410000,0.358214,0.132381,0.140000

In [262]:
genre_platform_sales_reset = genre_platform_sales.reset_index().melt(  #eshapes a DataFrame from wide format (platforms as separate columns) into long format (platforms as rows).
    id_vars='genre',
    var_name='platform',
    value_name='avg_sales'
)

fig_bar = px.bar(
    genre_platform_sales_reset,
    x='genre',
    y='avg_sales',
    color='platform',
    title="Average Global Sales by Genre and Platform (Stacked Bar)",
    labels={'avg_sales':'Avg Global Sales', 'genre':'Genre'},
    template='plotly_white'
)
fig_bar.show()

##### Genre or platform preference Analysis:

In [263]:

fig_heatmap = px.imshow(
    genre_platform_sales,
    labels=dict(x="Platform", y="Genre", color="Avg Global Sales"),
    title="Average Global Sales by Genre and Platform (Heatmap)",
    color_continuous_scale=my_colors 
)
fig_heatmap.show()

###### elafbhaa0@gmail.com